using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Data;
using Microsoft.Win32;

internal sealed class DpsHistorySummary {
    internal DpsHistoryRecord Record;internal string PlayerFilter;
    public string Started {get{return DpsHistory.LocalTime(Record.Started).ToString("dd MMM · HH:mm:ss",CultureInfo.CurrentCulture);}}
    public double Duration {get{return Record.Duration;}}
    public int Players {get{int value=0;foreach(var p in Record.Players)if(PlayerFilter==null||p.Name==PlayerFilter)value++;return value;}}
    public long Damage {get{long value=0;foreach(var p in Record.Players)if(PlayerFilter==null||p.Name==PlayerFilter)value+=p.Damage;return value;}}
    public long Healing {get{long value=0;foreach(var p in Record.Players)if(PlayerFilter==null||p.Name==PlayerFilter)value+=p.Healing;return value;}}
    public long Received {get{long value=0;foreach(var p in Record.Players)if(PlayerFilter==null||p.Name==PlayerFilter)value+=p.HealingReceived;return value;}}
}
internal sealed class DpsHistoryRoleConverter:IValueConverter {
    readonly string language;internal DpsHistoryRoleConverter(string value){language=value;}
    public object Convert(object value,Type type,object parameter,CultureInfo culture){byte role=(byte)value;return UiLanguage.Text(role==3?"Tank":role==2?"Healer / support":role==1?"Damage":"Unknown",language);}
    public object ConvertBack(object value,Type type,object parameter,CultureInfo culture){throw new NotSupportedException();}
}
internal sealed class DpsHistoryPane:Grid {
    readonly EnergyOverlay owner;readonly Window window;readonly CheckBox autoDelete=new CheckBox();readonly SettingsNumber age=new SettingsNumber("Delete records older than",1,3650,0,1),maximum=new SettingsNumber("Maximum records",1,1000,0,1);
    readonly ComboBox unit=new ComboBox{Width=108,Height=34},playerPicker=new ComboBox{Width=190,Height=34};readonly DataGrid encounters=Table(145),players=Table(235);readonly ScrollViewer scroller;readonly TextBlock count=SettingsVisual.Text("",12,"#929CAD"),detail=SettingsVisual.Text("",11,"#8994A6"),message=SettingsVisual.Text("",11,"#C5A783");readonly Button export,delete,clear;
    long revision=-1;int savedCount;bool loading;string language,playerFilter;DpsHistoryRecord selected;
    internal DpsHistoryPane(EnergyOverlay parent,Window settings){owner=parent;window=settings;var content=new StackPanel{Margin=new Thickness(0,0,12,0)};scroller=new ScrollViewer{Content=content,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};scroller.SetResourceReference(FrameworkElement.StyleProperty,"SlimScroll");Children.Add(scroller);
        var retention=new StackPanel();retention.Children.Add(SettingsVisual.Text("STORAGE",11,"#929CAD"));retention.Children.Add(Row("Automatically delete old records",autoDelete));
        var ageTools=new StackPanel{Orientation=Orientation.Horizontal};ageTools.Children.Add(age);unit.Margin=new Thickness(8,0,0,0);unit.Items.Add(new ComboBoxItem{Content="Hours",Tag="hours"});unit.Items.Add(new ComboBoxItem{Content="Days",Tag="days"});ageTools.Children.Add(unit);retention.Children.Add(Row("Delete records older than",ageTools));retention.Children.Add(Row("Maximum records",maximum));content.Children.Add(SettingsVisual.Card(retention,new Thickness(16,10,16,10)));
        var note=SettingsVisual.Text("Each fight is saved after the configured combat inactivity timeout. Resets, area changes and closing the helper save the unfinished fight with its end reason. Records survive restarts and include all identified players, regardless of the widget filter. At the storage limit, the oldest record is removed. Optional age cleanup runs at startup and once a minute. Deleting records cannot be undone.",11,"#8994A6");note.Margin=new Thickness(2,12,2,14);content.Children.Add(note);
        count.Margin=new Thickness(2,0,0,8);content.Children.Add(count);content.Children.Add(Row("Filter by player",playerPicker));playerPicker.SelectionChanged+=delegate{if(loading)return;var item=playerPicker.SelectedItem as ComboBoxItem;playerFilter=item==null?null:item.Tag as string;Refresh(true);};var actions=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,0,0,10)};export=SettingsVisual.Button("Export TXT",Export);export.ToolTip="Exports the selected fight using the player filter.";delete=SettingsVisual.Button("Delete record",DeleteSelected);delete.ToolTip="Deletes the entire fight, including all its players.";clear=SettingsVisual.Button("Clear all history",delegate{owner.CombatHistory.Clear();Refresh(true);});foreach(var b in new[]{export,delete,clear}){b.Margin=new Thickness(0,0,8,0);actions.Children.Add(b);}content.Children.Add(actions);
        content.Children.Add(SettingsVisual.Card(encounters,new Thickness(8)));detail.Margin=new Thickness(2,12,2,10);content.Children.Add(detail);content.Children.Add(SettingsVisual.Card(players,new Thickness(8)));message.Margin=new Thickness(2,10,2,0);content.Children.Add(message);
        autoDelete.Click+=delegate{Changed();};age.Changed+=Changed;maximum.Changed+=Changed;unit.SelectionChanged+=delegate{Changed();};encounters.SelectionChanged+=delegate{var row=encounters.SelectedItem as DpsHistorySummary;selected=row==null?null:row.Record;ShowSelected();};Reload();
    }
    static DataGrid Table(double height){return new DataGrid{Height=height,AutoGenerateColumns=false,IsReadOnly=true,CanUserAddRows=false,CanUserDeleteRows=false,EnableRowVirtualization=true,EnableColumnVirtualization=true,SelectionMode=DataGridSelectionMode.Single,SelectionUnit=DataGridSelectionUnit.FullRow,HeadersVisibility=DataGridHeadersVisibility.Column};}
    static Grid Row(string text,FrameworkElement control){var row=new Grid{MinHeight=45,Margin=new Thickness(0,4,0,4)};row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});row.Children.Add(SettingsVisual.Text(text,12));Grid.SetColumn(control,1);row.Children.Add(control);AutomationProperties.SetName(control,text);return row;}
    void Changed(){if(loading)return;var c=owner.Configuration;c.Dps.HistoryAutoDelete=autoDelete.IsChecked==true;c.Dps.HistoryAge=(int)age.Value;c.Dps.HistoryMaxRecords=(int)maximum.Value;var item=unit.SelectedItem as ComboBoxItem;if(item!=null)c.Dps.HistoryAgeUnit=(string)item.Tag;owner.ApplyConfiguration(c);Reload();}
    internal void Reload(){loading=true;try{var o=owner.Configuration.Dps;autoDelete.IsChecked=o.HistoryAutoDelete;age.Value=o.HistoryAge;maximum.Value=o.HistoryMaxRecords;unit.SelectedIndex=o.HistoryAgeUnit=="hours"?0:1;age.IsEnabled=unit.IsEnabled=o.HistoryAutoDelete;if(language!=owner.Language){language=owner.Language;Columns();revision=-1;}UiLanguage.Apply(this,owner.Language);}finally{loading=false;}Refresh();}
    string T(string text){return UiLanguage.Text(text,owner.Language);}
    void Column(DataGrid table,string label,string property,double width,string format=null){var binding=new Binding(property){TargetNullValue="—"};if(format!=null)binding.StringFormat=format;var column=new DataGridTextColumn{Header=T(label),Binding=binding,Width=new DataGridLength(width)};table.Columns.Add(column);}
    void Columns(){encounters.Columns.Clear();Column(encounters,"Started","Started",160);Column(encounters,"Duration","Duration",80,"{0:0.0} s");Column(encounters,"Players","Players",65);Column(encounters,"Damage","Damage",100,"{0:N0}");Column(encounters,"Healing done","Healing",110,"{0:N0}");Column(encounters,"Healing received","Received",110,"{0:N0}");
        var factory=new FrameworkElementFactory(typeof(Button));factory.SetValue(ContentControl.ContentProperty,"×");factory.SetValue(FrameworkElement.ToolTipProperty,T("Delete record"));factory.SetValue(Control.PaddingProperty,new Thickness(8,2,8,2));factory.AddHandler(Button.ClickEvent,new RoutedEventHandler(delegate(object sender,RoutedEventArgs e){var row=((Button)sender).DataContext as DpsHistorySummary;if(row!=null){owner.CombatHistory.Delete(row.Record.Id);Refresh(true);}e.Handled=true;}));encounters.Columns.Add(new DataGridTemplateColumn{Header="",Width=42,CellTemplate=new DataTemplate{VisualTree=factory}});
        players.Columns.Clear();Column(players,"Name","Name",120);players.Columns.Add(new DataGridTextColumn{Header=T("Role"),Binding=new Binding("Role"){Converter=new DpsHistoryRoleConverter(owner.Language)},Width=115});Column(players,"Damage","Damage",95,"{0:N0}");Column(players,"DPS","Dps",80,"{0:N1}");Column(players,"Periodic damage","PeriodicDamage",115,"{0:N0}");Column(players,"Damage crit. %","DamageCritShare",110,"{0:0.0}%");Column(players,"Damage crit. rate","DamageCritRate",120,"{0:0.0}%");Column(players,"Healing done","Healing",110,"{0:N0}");Column(players,"HPS","Hps",80,"{0:N1}");Column(players,"Healing received","HealingReceived",120,"{0:N0}");Column(players,"Received HPS","ReceivedHps",110,"{0:N1}");Column(players,"Healing crit. %","HealingCritShare",115,"{0:0.0}%");Column(players,"Healing crit. rate","HealingCritRate",125,"{0:0.0}%");Column(players,"Received crit. %","ReceivedCritShare",120,"{0:0.0}%");Column(players,"Received crit. rate","ReceivedCritRate",130,"{0:0.0}%");
        foreach(var pair in new[]{new[]{"Impacts","Hits"},new[]{"Critical damage impacts","Criticals"},new[]{"Eligible damage impacts","DamageEvents"},new[]{"Primary damage","DamagePrimary"},new[]{"Critical primary damage","DamageCritical"},new[]{"Eligible healing impacts","HealingEvents"},new[]{"Critical healing impacts","HealingCriticals"},new[]{"Primary healing","HealingPrimary"},new[]{"Critical primary healing","HealingCritical"},new[]{"Eligible received impacts","ReceivedEvents"},new[]{"Critical received impacts","ReceivedCriticals"},new[]{"Primary received healing","ReceivedPrimary"},new[]{"Critical primary received healing","ReceivedCritical"}})Column(players,pair[0],pair[1],155,"{0:N0}");Column(players,"Actor ID","Actor",75);
    }
    internal void Refresh(bool force=false){if(!force&&Visibility!=Visibility.Visible)return;long current=owner.CombatHistory.Revision;if(force||revision!=current){revision=current;string id=selected==null?null:selected.Id;var records=owner.CombatHistory.Read();savedCount=records.Count;var names=new SortedSet<string>(StringComparer.OrdinalIgnoreCase);foreach(var r in records)foreach(var p in r.Players)if(p.Name!=null)names.Add(p.Name);bool wasLoading=loading;loading=true;try{playerPicker.Items.Clear();var all=new ComboBoxItem{Content=T("All players")};playerPicker.Items.Add(all);ComboBoxItem chosen=all;foreach(string name in names){var item=new ComboBoxItem{Content=name,Tag=name};playerPicker.Items.Add(item);if(name==playerFilter)chosen=item;}playerPicker.SelectedItem=chosen;playerFilter=chosen.Tag as string;}finally{loading=wasLoading;}var rows=new List<DpsHistorySummary>();foreach(var record in records){bool include=playerFilter==null;foreach(var p in record.Players)if(p.Name==playerFilter)include=true;if(include)rows.Add(new DpsHistorySummary{Record=record,PlayerFilter=playerFilter});}encounters.ItemsSource=rows;DpsHistorySummary match=null;foreach(var row in rows)if(row.Record.Id==id){match=row;break;}encounters.SelectedItem=match??(rows.Count>0?rows[0]:null);count.Text=T("Saved fights")+": "+records.Count+" / "+owner.Configuration.Dps.HistoryMaxRecords;clear.IsEnabled=records.Count>0;ShowSelected();}count.Text=T("Saved fights")+": "+savedCount+" / "+owner.Configuration.Dps.HistoryMaxRecords;string error=owner.CombatHistory.Error;if(error!=null)message.Text=T("History storage error")+": "+error;}
    void ShowSelected(){export.IsEnabled=delete.IsEnabled=selected!=null;var visible=new List<DpsHistoryPlayer>();if(selected!=null)foreach(var p in selected.Players)if(playerFilter==null||p.Name==playerFilter)visible.Add(p);players.ItemsSource=visible;if(selected==null){detail.Text=T("No saved fights yet. Fight while the DPS meter is enabled, then wait for its combat timeout.");return;}detail.Text=T("Started")+": "+DpsHistory.LocalTime(selected.Started).ToString("yyyy-MM-dd HH:mm:ss")+" · "+T("Ended")+": "+DpsHistory.LocalTime(selected.Ended).ToString("HH:mm:ss")+" · "+T("Duration")+": "+selected.Duration.ToString("0.0",CultureInfo.InvariantCulture)+" s\n"+T("End reason")+": "+T(selected.Reason)+"\n"+T("One row per player. Scroll the table horizontally to see all statistics.")+"\n"+T("Partial metrics. Critical percentages use eligible primary direct impacts; healing is raw restoration. Unknown effects, effective healing, overhealing and unvalidated boss mechanics are not included.");}
    void DeleteSelected(){if(selected==null)return;owner.CombatHistory.Delete(selected.Id);Refresh(true);}
    internal void RenderDetails(string path){scroller.ScrollToBottom();SettingsVisual.RenderPreview(window,path);scroller.ScrollToTop();}
    internal void VerifyPlayerFilter(){owner.CombatHistory.Add(DpsVerification.HistorySample(DpsHistory.UtcNow()));Refresh(true);ComboBoxItem chosen=null;foreach(ComboBoxItem item in playerPicker.Items)if((string)item.Tag=="Player Two")chosen=item;playerPicker.SelectedItem=chosen;if(players.Items.Count!=1||((DpsHistoryPlayer)players.Items[0]).Name!="Player Two"||((DpsHistorySummary)encounters.Items[0]).Healing!=43000)throw new Exception("History player filter must select individual metrics in both tables");string text=DpsHistory.Text(selected,owner.Language,playerFilter);if(!text.Contains("Player Two")||text.Contains("Player One"))throw new Exception("Player-filtered TXT export must exclude other player rows");playerPicker.SelectedIndex=0;owner.CombatHistory.Clear();Refresh(true);}
    void Export(){if(selected==null)return;var dialog=new SaveFileDialog{Title=T("Export combat record"),Filter="Text files (*.txt)|*.txt",DefaultExt=".txt",AddExtension=true,FileName="Aion2Helper-combat-"+DpsHistory.LocalTime(selected.Started).ToString("yyyyMMdd-HHmmss",CultureInfo.InvariantCulture)+".txt"};bool? result=window==null?dialog.ShowDialog():dialog.ShowDialog(window);if(result!=true)return;try{File.WriteAllText(dialog.FileName,DpsHistory.Text(selected,owner.Language,playerFilter),new System.Text.UTF8Encoding(true));message.Text=T("Record exported.");}catch(IOException ex){message.Text=T("Export failed")+": "+ex.Message;}catch(UnauthorizedAccessException ex){message.Text=T("Export failed")+": "+ex.Message;}}
    internal void Verify(){var original=owner.Configuration;autoDelete.IsChecked=true;age.Value=2;maximum.Value=3;unit.SelectedIndex=0;Changed();Reload();if(!owner.Configuration.Dps.HistoryAutoDelete||owner.Configuration.Dps.HistoryAgeUnit!="hours"||!age.IsEnabled||owner.Configuration.Dps.HistoryMaxRecords!=3)throw new Exception("History settings failed to apply");owner.ApplyConfiguration(original);Reload();if(age.IsEnabled!=original.Dps.HistoryAutoDelete)throw new Exception("History cleanup activation failed to reload");VerifyPlayerFilter();}
}
