using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Threading;
using System.Web.Script.Serialization;

// Immutable after capture. Public fields are the local JSON schema, not packet
// data or a raw traffic log. Keep it separate from settings and undo history.
internal sealed class DpsHistoryPlayer {
    public uint Actor {get;set;}public string Name {get;set;}public byte Role {get;set;}
    public long Damage {get;set;}public long PeriodicDamage {get;set;}public long DamagePrimary {get;set;}public long DamageCritical {get;set;}public long Healing {get;set;}public long HealingReceived {get;set;}public long HealingPrimary {get;set;}public long HealingCritical {get;set;}public long ReceivedPrimary {get;set;}public long ReceivedCritical {get;set;}
    public int Hits {get;set;}public int Criticals {get;set;}public int DamageEvents {get;set;}public int HealingEvents {get;set;}public int HealingCriticals {get;set;}public int ReceivedEvents {get;set;}public int ReceivedCriticals {get;set;}
    public double Dps {get;set;}public double Hps {get;set;}public double ReceivedHps {get;set;}
    internal static DpsHistoryPlayer Capture(DpsSignal.Row row,string name,byte role,double duration){return new DpsHistoryPlayer{Actor=row.Actor,Name=name,Role=role,Damage=row.Damage,PeriodicDamage=row.PeriodicDamage,DamagePrimary=row.DamagePrimary,DamageCritical=row.DamageCritical,Healing=row.Healing,HealingReceived=row.HealingReceived,HealingPrimary=row.HealingPrimary,HealingCritical=row.HealingCritical,ReceivedPrimary=row.ReceivedPrimary,ReceivedCritical=row.ReceivedCritical,Hits=row.Hits,Criticals=row.Criticals,DamageEvents=row.DamageEvents,HealingEvents=row.HealingEvents,HealingCriticals=row.HealingCriticals,ReceivedEvents=row.ReceivedEvents,ReceivedCriticals=row.ReceivedCriticals,Dps=row.Damage/duration,Hps=row.Healing/duration,ReceivedHps=row.HealingReceived/duration};}
    internal DpsSignal.Row Row(){return new DpsSignal.Row{Actor=Actor,Name=Name,Role=Role,DamagePrimary=DamagePrimary,DamageCritical=DamageCritical,DamageEvents=DamageEvents,Criticals=Criticals,HealingPrimary=HealingPrimary,HealingCritical=HealingCritical,HealingEvents=HealingEvents,HealingCriticals=HealingCriticals,ReceivedPrimary=ReceivedPrimary,ReceivedCritical=ReceivedCritical,ReceivedEvents=ReceivedEvents,ReceivedCriticals=ReceivedCriticals};}
    public double? DamageCritShare {get{return DpsSignal.CriticalShare(Row(),"damage");}}
    public double? DamageCritRate {get{return DpsSignal.CriticalRate(Row(),"damage");}}
    public double? HealingCritShare {get{return DpsSignal.CriticalShare(Row(),"healing");}}
    public double? HealingCritRate {get{return DpsSignal.CriticalRate(Row(),"healing");}}
    public double? ReceivedCritShare {get{return DpsSignal.CriticalShare(Row(),"received");}}
    public double? ReceivedCritRate {get{return DpsSignal.CriticalRate(Row(),"received");}}
}
internal sealed class DpsHistoryRecord {
    public string Id,Reason,Scope;public double Started,Ended,Duration;public uint Map,SelfActor;
    public bool PartyKnown,PartyRecovered;public List<uint> Party=new List<uint>();public List<DpsHistoryPlayer> Players=new List<DpsHistoryPlayer>();
    public long Pending,DirectFrames,ParsedDirect,UnknownTargets,UnknownSources;
}
internal sealed class DpsHistory:IDisposable {
    sealed class FileData {public int Version=1;public List<DpsHistoryRecord> Records=new List<DpsHistoryRecord>();}
    readonly object gate=new object();readonly List<DpsHistoryRecord> records=new List<DpsHistoryRecord>();readonly string path;readonly bool persistent;
    readonly ManualResetEvent idle=new ManualResetEvent(true);DpsOptions options;long revision,savedRevision;bool writing,disposed,loadBlocked;double nextCleanup;string error;
    internal DpsHistory(string root,DpsOptions settings,bool persist=true){path=Path.Combine(root,"combat-history.json");persistent=persist;options=settings.Copy();options.Normalize();if(persistent)Load();Prune(UtcNow());}
    internal static double UtcNow(){return (DateTime.UtcNow-new DateTime(1970,1,1)).TotalSeconds;}
    static JavaScriptSerializer Serializer(){return new JavaScriptSerializer{MaxJsonLength=64*1024*1024,RecursionLimit=32};}
    internal long Revision {get{lock(gate)return revision;}}
    internal string Error {get{lock(gate)return error;}}
    internal List<DpsHistoryRecord> Read(){lock(gate)return new List<DpsHistoryRecord>(records);}
    internal void Add(DpsHistoryRecord record){if(record==null||record.Players.Count==0)return;lock(gate){if(disposed)return;records.Insert(0,record);records.Sort(delegate(DpsHistoryRecord a,DpsHistoryRecord b){return b.Ended.CompareTo(a.Ended);});revision++;PruneLocked(UtcNow());}SaveAsync();}
    internal bool Delete(string id){bool removed;lock(gate){removed=records.RemoveAll(delegate(DpsHistoryRecord r){return r.Id==id;})>0;if(removed)revision++;}if(removed)SaveAsync();return removed;}
    internal void Clear(){lock(gate){if(records.Count==0)return;records.Clear();revision++;}SaveAsync();}
    internal void Configure(DpsOptions next){lock(gate){options=next.Copy();options.Normalize();PruneLocked(UtcNow());}SaveAsync();}
    internal void Maintain(double now){lock(gate){if(now<nextCleanup)return;nextCleanup=now+60;PruneLocked(now);}SaveAsync();}
    internal void Prune(double now){lock(gate)PruneLocked(now);SaveAsync();}
    void PruneLocked(double now){bool changed=false;if(options.HistoryAutoDelete){double age=options.HistoryAge*(options.HistoryAgeUnit=="hours"?3600.0:86400.0);changed=records.RemoveAll(delegate(DpsHistoryRecord r){return r.Ended<now-age;})>0;}if(records.Count>options.HistoryMaxRecords){records.RemoveRange(options.HistoryMaxRecords,records.Count-options.HistoryMaxRecords);changed=true;}if(changed)revision++;}
    void Load(){try{if(!File.Exists(path))return;if(new FileInfo(path).Length>64*1024*1024)throw new InvalidDataException("History file exceeds the size limit");var data=Serializer().Deserialize<FileData>(File.ReadAllText(path,Encoding.UTF8));if(data==null||data.Version!=1||data.Records==null||data.Records.Count>1000)throw new InvalidDataException("Unsupported history file");var ids=new HashSet<string>();foreach(var r in data.Records){if(r==null||string.IsNullOrEmpty(r.Id)||!ids.Add(r.Id)||r.Players==null||r.Players.Count>128||r.Started<0||double.IsNaN(r.Started)||double.IsInfinity(r.Started)||r.Ended<r.Started||double.IsNaN(r.Ended)||double.IsInfinity(r.Ended)||r.Ended>253402214399||r.Party==null||r.Party.Count>12)throw new InvalidDataException("Invalid history record");foreach(var p in r.Players)if(p==null||p.Actor==0||p.Name!=null&&p.Name.Length>100||p.Damage<0||p.Healing<0||p.HealingReceived<0||p.DamagePrimary<0||p.DamageCritical<0||p.DamageCritical>p.DamagePrimary||p.DamagePrimary>p.Damage||p.PeriodicDamage<0||p.PeriodicDamage>p.Damage||p.HealingPrimary<0||p.HealingCritical<0||p.HealingCritical>p.HealingPrimary||p.HealingPrimary>p.Healing||p.ReceivedPrimary<0||p.ReceivedCritical<0||p.ReceivedCritical>p.ReceivedPrimary||p.ReceivedPrimary>p.HealingReceived||p.DamageEvents<0||p.Criticals<0||p.Criticals>p.DamageEvents||p.HealingEvents<0||p.HealingCriticals<0||p.HealingCriticals>p.HealingEvents||p.ReceivedEvents<0||p.ReceivedCriticals<0||p.ReceivedCriticals>p.ReceivedEvents)throw new InvalidDataException("Invalid history player");r.Duration=Math.Max(1,r.Ended-r.Started);foreach(var p in r.Players){p.Dps=p.Damage/r.Duration;p.Hps=p.Healing/r.Duration;p.ReceivedHps=p.HealingReceived/r.Duration;}}records.AddRange(data.Records);records.Sort(delegate(DpsHistoryRecord a,DpsHistoryRecord b){return b.Ended.CompareTo(a.Ended);});}catch(Exception ex){if(!(ex is IOException||ex is UnauthorizedAccessException||ex is ArgumentException||ex is InvalidOperationException||ex is FormatException||ex is OverflowException))throw;try{if(File.Exists(path))File.Move(path,Path.Combine(Path.GetDirectoryName(path),"combat-history.corrupt-"+DateTime.UtcNow.ToString("yyyyMMdd-HHmmss",CultureInfo.InvariantCulture)+"-"+Guid.NewGuid().ToString("N")+".json"));error="Unreadable history was preserved in a backup.";}catch(IOException){loadBlocked=true;error="History could not be read. The original file was preserved.";}catch(UnauthorizedAccessException){loadBlocked=true;error="History could not be read. The original file was preserved.";}}}
    void SaveAsync(){lock(gate){if(!persistent||disposed||loadBlocked||writing||revision==savedRevision)return;writing=true;idle.Reset();}ThreadPool.QueueUserWorkItem(delegate{SaveWorker();});}
    void SaveWorker(){try{while(true){List<DpsHistoryRecord> copy;long version;lock(gate){copy=new List<DpsHistoryRecord>(records);version=revision;}string text=Serializer().Serialize(new FileData{Records=copy});string temp=path+".tmp";File.WriteAllText(temp,text,new UTF8Encoding(false));if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);lock(gate){savedRevision=version;error=null;if(version==revision){writing=false;idle.Set();return;}}}}catch(Exception ex){lock(gate){error="History could not be saved: "+ex.Message;writing=false;idle.Set();}}}
    internal bool Flush(int timeout=10000){SaveAsync();return idle.WaitOne(timeout);}
    public void Dispose(){lock(gate){if(disposed)return;}bool finished=Flush();lock(gate)disposed=true;if(finished)idle.Dispose();/* A timed-out writer still owns the wait handle. */}
    internal static DateTime LocalTime(double ts){return new DateTime(1970,1,1,0,0,0,DateTimeKind.Utc).AddSeconds(ts).ToLocalTime();}
    internal static string Text(DpsHistoryRecord record,string language,string playerFilter=null){Func<string,string> t=delegate(string key){return UiLanguage.Text(key,language);};var b=new StringBuilder();b.AppendLine("Aion 2 Helper · "+t("Combat history"));b.AppendLine(t("Started")+": "+LocalTime(record.Started).ToString("yyyy-MM-dd HH:mm:ss zzz",CultureInfo.InvariantCulture));b.AppendLine(t("Ended")+": "+LocalTime(record.Ended).ToString("yyyy-MM-dd HH:mm:ss zzz",CultureInfo.InvariantCulture));b.AppendLine(t("Duration")+": "+record.Duration.ToString("0.0",CultureInfo.InvariantCulture)+" s");b.AppendLine(t("End reason")+": "+t(record.Reason));b.AppendLine(t("Map ID")+": "+record.Map+" · "+t("Self ID")+": "+record.SelfActor);b.AppendLine(t("Party IDs")+": "+string.Join(", ",record.Party));b.AppendLine(t("Party known")+": "+record.PartyKnown+" · "+t("Recovered party")+": "+record.PartyRecovered);b.AppendLine(t("Player filter")+": "+(playerFilter??t("All players")));b.AppendLine(t("Widget filter")+": "+t(record.Scope=="self"?"Self":record.Scope=="party"?"Party":"Nearby players"));b.AppendLine(t("History includes all identified players received by your game, independently of the widget filter."));b.AppendLine(t("Diagnostic counters are cumulative for the reader session."));b.AppendLine("directFrames="+record.DirectFrames+"; parsedDirect="+record.ParsedDirect+"; pending="+record.Pending+"; unknownTargets="+record.UnknownTargets+"; unknownSources="+record.UnknownSources);b.AppendLine(t("Partial metrics. Critical percentages use eligible primary direct impacts; healing is raw restoration. Unknown effects, effective healing, overhealing and unvalidated boss mechanics are not included."));
        string[] labels={"Name","Actor ID","Role","Damage","DPS","Periodic damage","Impacts","Critical damage impacts","Eligible damage impacts","Primary damage","Critical primary damage","Damage crit. %","Damage crit. rate","Healing done","HPS","Healing received","Received HPS","Healing crit. %","Healing crit. rate","Received crit. %","Received crit. rate","Eligible healing impacts","Critical healing impacts","Primary healing","Critical primary healing","Eligible received impacts","Critical received impacts","Primary received healing","Critical primary received healing"};for(int i=0;i<labels.Length;i++)labels[i]=t(labels[i]);b.AppendLine();b.AppendLine(string.Join("\t",labels));foreach(var p in record.Players){if(playerFilter!=null&&p.Name!=playerFilter)continue;object[] values={p.Name??"?",p.Actor,t(p.Role==3?"Tank":p.Role==2?"Healer / support":p.Role==1?"Damage":"Unknown"),p.Damage,p.Dps.ToString("0.0",CultureInfo.InvariantCulture),p.PeriodicDamage,p.Hits,p.Criticals,p.DamageEvents,p.DamagePrimary,p.DamageCritical,DpsDesign.Percent(p.DamageCritShare),DpsDesign.Percent(p.DamageCritRate),p.Healing,p.Hps.ToString("0.0",CultureInfo.InvariantCulture),p.HealingReceived,p.ReceivedHps.ToString("0.0",CultureInfo.InvariantCulture),DpsDesign.Percent(p.HealingCritShare),DpsDesign.Percent(p.HealingCritRate),DpsDesign.Percent(p.ReceivedCritShare),DpsDesign.Percent(p.ReceivedCritRate),p.HealingEvents,p.HealingCriticals,p.HealingPrimary,p.HealingCritical,p.ReceivedEvents,p.ReceivedCriticals,p.ReceivedPrimary,p.ReceivedCritical};var cells=new string[values.Length];for(int i=0;i<values.Length;i++)cells[i]=Convert.ToString(values[i],CultureInfo.InvariantCulture).Replace("\t"," ").Replace("\r"," ").Replace("\n"," ");b.AppendLine(string.Join("\t",cells));}return b.ToString();}
}
