using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using Drawing=System.Drawing;

internal sealed class DpsSettingsPane:Grid {
    readonly EnergyOverlay owner;readonly Window window;readonly CheckBox enabled=new CheckBox(),background=new CheckBox(),roleColors=new CheckBox(),autoHide=new CheckBox(),fade=new CheckBox(),smooth=new CheckBox(),showSelfAsYou=new CheckBox(),pinSelfFirst=new CheckBox();readonly ComboBox scope=new ComboBox{Width=190,Height=38},view=new ComboBox{Width=190,Height=38};readonly TextBox selfName=new TextBox{Width=190,Height=34};
    readonly StackPanel controls=new StackPanel();readonly ScrollViewer scroller;readonly Image preview=new Image{Height=170,Stretch=System.Windows.Media.Stretch.None};readonly Border previewCard;readonly TextBlock state=SettingsVisual.Text("",11,"#8994A6");readonly Button color,damageColor,healerColor,tankColor;
    readonly Dictionary<string,SettingsNumber> numbers=new Dictionary<string,SettingsNumber>();bool loading;DpsOptions loaded;string loadedLanguage,colorHex,damageHex,healerHex,tankHex;
    readonly DpsHistoryPane history;readonly Grid activation;readonly Button settingsTab,historyTab;bool historySelected;
    internal DpsSettingsPane(EnergyOverlay parent,Window settings){owner=parent;window=settings;
        RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});
        var tabs=new Grid{Margin=new Thickness(0,0,0,12)};tabs.ColumnDefinitions.Add(new ColumnDefinition());tabs.ColumnDefinitions.Add(new ColumnDefinition());settingsTab=SettingsVisual.Button("Configuration",delegate{SelectHistory(false);});historyTab=SettingsVisual.Button("History",delegate{SelectHistory(true);});settingsTab.Margin=new Thickness(0,0,4,0);historyTab.Margin=new Thickness(4,0,0,0);Grid.SetColumn(historyTab,1);tabs.Children.Add(settingsTab);tabs.Children.Add(historyTab);Children.Add(tabs);
        activation=Row("Enable DPS meter");Grid.SetRow(activation,1);Children.Add(activation);Grid.SetColumn(enabled,1);activation.Children.Add(enabled);AutomationProperties.SetName(enabled,"Enable DPS meter");enabled.Click+=delegate{if(loading)return;var c=owner.Configuration;c.Dps.Enabled=enabled.IsChecked==true;owner.ApplyConfiguration(c);};
        var sample=new StackPanel();sample.Children.Add(SettingsVisual.Text("PREVIEW",10,"#929CAD"));sample.Children.Add(preview);sample.Children.Add(SettingsVisual.Text("Sample value · not a game reading",11,"#8994A6"));previewCard=SettingsVisual.Card(sample,new Thickness(18,10,18,10));Grid.SetRow(previewCard,2);Children.Add(previewCard);
        controls.Margin=new Thickness(0,0,12,0);scroller=new ScrollViewer{Content=controls,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};scroller.SetResourceReference(FrameworkElement.StyleProperty,"SlimScroll");Grid.SetRow(scroller,3);Children.Add(scroller);
        history=new DpsHistoryPane(owner,window){Visibility=Visibility.Collapsed};Grid.SetRow(history,1);Grid.SetRowSpan(history,3);Children.Add(history);
        var group=Group("MEASUREMENT");var row=Row("Show players");group.Children.Add(row);Grid.SetColumn(scope,1);row.Children.Add(scope);scope.Items.Add(new ComboBoxItem{Content="Self",Tag="self"});scope.Items.Add(new ComboBoxItem{Content="Party",Tag="party"});scope.Items.Add(new ComboBoxItem{Content="Nearby players",Tag="global"});AutomationProperties.SetName(scope,"Show players");scope.SelectionChanged+=delegate{Changed();};
        row=Row("Your character name","Optional · leave empty for automatic detection.");group.Children.Add(row);Grid.SetColumn(selfName,1);row.Children.Add(selfName);AutomationProperties.SetName(selfName,"Your character name");selfName.MaxLength=24;selfName.LostKeyboardFocus+=delegate{Changed();};
        Number(group,"Refresh","Refresh interval","ms",250,2000,50);Number(group,"Idle","End encounter after idle","s",1,120,1);
        row=Row("Combat view");group.Children.Add(row);Grid.SetColumn(view,1);row.Children.Add(view);view.Items.Add(new ComboBoxItem{Content="Damage",Tag="damage"});view.Items.Add(new ComboBoxItem{Content="Healing done",Tag="healing"});view.Items.Add(new ComboBoxItem{Content="Healing received",Tag="received"});AutomationProperties.SetName(view,"Combat view");view.SelectionChanged+=delegate{Changed();};
        var metrics=SettingsVisual.Text("Crit. %: share of primary direct damage or healing from criticals. Crit. rate: observed critical frequency. Additional impacts and periodic ticks are excluded from both percentages.",11,"#8994A6");metrics.Margin=new Thickness(0,6,0,12);group.Children.Add(metrics);
        var limitation=SettingsVisual.Text("Alpha: partial damage and raw healing from supported skills. Identified damage-over-time effects are included automatically. Other effects, effective healing and overhealing are still being validated. Nearby covers only combat data received by your game.",11,"#C5A783");limitation.Margin=new Thickness(0,8,0,12);group.Children.Add(limitation);state.Margin=new Thickness(0,5,0,12);group.Children.Add(state);
        var reset=SettingsVisual.Button("Reset encounter",owner.ResetDpsEncounter);reset.HorizontalAlignment=HorizontalAlignment.Left;reset.Margin=new Thickness(0,0,0,12);group.Children.Add(reset);
        group=Group("APPEARANCE");Toggle(group,"Show my name as You",showSelfAsYou,"Uses the language selected in General settings.");Toggle(group,"Keep my character first",pinSelfFirst,"Other players remain sorted by the selected combat view.");Toggle(group,"Colors by class role",roleColors,"Tank: Gladiator / Templar. Healer / support: Cleric / Chanter. Other classes: damage.");
        damageColor=ColorRow(group,"Damage color",delegate{PickRoleColor(1);});healerColor=ColorRow(group,"Healer / support color",delegate{PickRoleColor(2);});tankColor=ColorRow(group,"Tank color",delegate{PickRoleColor(3);});
        color=ColorRow(group,"Fallback bar color",PickColor);
        row=Row("Dark background");group.Children.Add(row);Grid.SetColumn(background,1);row.Children.Add(background);background.Click+=delegate{Changed();};Number(group,"Opacity","Background opacity","%",0,100,1);Number(group,"Rows","Visible rows","",1,10,1);
        group=Group("VISIBILITY & ANIMATION");Toggle(group,"Hide automatically out of combat",autoHide,"Uses the players selected by your filter. Unlocked widgets stay visible.");Number(group,"HideAfter","Hide after inactivity","s",1,300,1);
        Toggle(group,"Fade in and out",fade);Number(group,"Fade","Fade duration","s",0,2,.01M,2);
        Toggle(group,"Smooth bar movement",smooth);Number(group,"Smooth","Bar smoothing time","s",0,2,.01M,2);
        group=Group("GEOMETRY");Number(group,"Width","Width","px",260,1600,1);Number(group,"Height","Height","px",110,900,1);Number(group,"X","Horizontal position","px",-100000,100000,1);Number(group,"Y","Vertical position","px",-100000,100000,1);
        foreach(var pair in numbers)pair.Value.Changed+=Changed;Reload();SelectHistory(false);
    }
    static Grid Row(string label,string note=null){var row=new Grid{MinHeight=57,Margin=new Thickness(0,5,0,5)};row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var labels=new StackPanel{VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0,0,20,0)};labels.Children.Add(SettingsVisual.Text(label));if(note!=null){var n=SettingsVisual.Text(note,11,"#8994A6");n.Margin=new Thickness(0,5,0,0);labels.Children.Add(n);}row.Children.Add(labels);return row;}
    StackPanel Group(string name){var title=SettingsVisual.Text(name,11,"#929CAD");title.Margin=new Thickness(2,5,0,9);controls.Children.Add(title);var stack=new StackPanel();controls.Children.Add(SettingsVisual.Card(stack,new Thickness(16,3,16,3)));return stack;}
    void Number(StackPanel group,string key,string label,string unit,decimal min,decimal max,decimal step,int precision=0){var row=Row(label);group.Children.Add(row);var side=new StackPanel{Orientation=Orientation.Horizontal};Grid.SetColumn(side,1);row.Children.Add(side);var n=new SettingsNumber(label,min,max,precision,step);numbers[key]=n;side.Children.Add(n);var units=SettingsVisual.Text(unit,11,"#8994A6");units.Width=28;units.Margin=new Thickness(7,0,0,0);side.Children.Add(units);}
    void Toggle(StackPanel group,string label,CheckBox box,string note=null){var row=Row(label,note);group.Children.Add(row);Grid.SetColumn(box,1);row.Children.Add(box);AutomationProperties.SetName(box,label);box.Click+=delegate{Changed();};}
    Button ColorRow(StackPanel group,string label,Action action){var row=Row(label);group.Children.Add(row);var button=SettingsVisual.Button("",action);button.Width=150;Grid.SetColumn(button,1);row.Children.Add(button);AutomationProperties.SetName(button,"Choose color: "+label);return button;}
    void Changed(){if(loading)return;var c=owner.Configuration;var item=scope.SelectedItem as ComboBoxItem;if(item!=null)c.Dps.Scope=(string)item.Tag;c.Dps.SelfName=selfName.Text;c.Dps.ShowSelfAsYou=showSelfAsYou.IsChecked==true;c.Dps.PinSelfFirst=pinSelfFirst.IsChecked==true;c.Dps.Background=background.IsChecked==true;var metric=view.SelectedItem as ComboBoxItem;if(metric!=null)c.Dps.View=(string)metric.Tag;c.Dps.Color=colorHex;c.Dps.RoleColors=roleColors.IsChecked==true;c.Dps.DamageColor=damageHex;c.Dps.HealerColor=healerHex;c.Dps.TankColor=tankHex;c.Dps.AutoHide=autoHide.IsChecked==true;c.Dps.Fade=fade.IsChecked==true;c.Dps.Smooth=smooth.IsChecked==true;c.Dps.HideAfterSeconds=(double)numbers["HideAfter"].Value;c.Dps.FadeSeconds=(double)numbers["Fade"].Value;c.Dps.SmoothingSeconds=(double)numbers["Smooth"].Value;c.Dps.RefreshIntervalMs=(int)numbers["Refresh"].Value;c.Dps.IdleSeconds=(int)numbers["Idle"].Value;c.Dps.BackgroundOpacity=(int)Math.Round((double)numbers["Opacity"].Value*255/100);c.Dps.MaxRows=(int)numbers["Rows"].Value;c.Dps.Bounds=new Drawing.Rectangle((int)numbers["X"].Value,(int)numbers["Y"].Value,(int)numbers["Width"].Value,(int)numbers["Height"].Value);owner.ApplyConfiguration(c);}
    void PickColor(){var picker=new HelperColorPicker(colorHex,"Fallback bar color",owner.Language){Owner=window};if(picker.ShowDialog()==true){colorHex=picker.SelectedHex;Changed();}}
    void PickRoleColor(int role){var picker=new HelperColorPicker(role==1?damageHex:role==2?healerHex:tankHex,role==1?"Damage color":role==2?"Healer / support color":"Tank color",owner.Language){Owner=window};if(picker.ShowDialog()==true){if(role==1)damageHex=picker.SelectedHex;else if(role==2)healerHex=picker.SelectedHex;else tankHex=picker.SelectedHex;Changed();}}
    static void Swatch(Button button,string hex){var swatch=new StackPanel{Orientation=Orientation.Horizontal};swatch.Children.Add(new Border{Width=17,Height=17,CornerRadius=new CornerRadius(5),Background=SettingsVisual.Brush(hex),Margin=new Thickness(0,0,9,0)});swatch.Children.Add(SettingsVisual.Text(hex,12,"#D1D6E0"));button.Content=swatch;}
    internal void SelectHistory(bool selected){historySelected=selected;activation.Visibility=previewCard.Visibility=scroller.Visibility=selected?Visibility.Collapsed:Visibility.Visible;history.Visibility=selected?Visibility.Visible:Visibility.Collapsed;settingsTab.Background=SettingsVisual.Brush(selected?"#183F4653":"#2867C7B0");historyTab.Background=SettingsVisual.Brush(selected?"#2867C7B0":"#183F4653");if(selected)history.Refresh(true);}
    internal void UpdateStatus(){string text=UiLanguage.Text(owner.DpsStatus,owner.Language);if(state.Text!=text)state.Text=text;if(historySelected)history.Refresh();}
    internal void Reload(){history.Reload();var o=owner.Configuration.Dps;if(loaded!=null&&DpsOptions.Same(loaded,o)&&loadedLanguage==owner.Language){UpdateStatus();return;}loading=true;try{loaded=o.Copy();loadedLanguage=owner.Language;enabled.IsChecked=o.Enabled;background.IsChecked=o.Background;view.SelectedIndex=o.View=="healing"?1:o.View=="received"?2:0;scope.SelectedIndex=o.Scope=="self"?0:o.Scope=="party"?1:2;selfName.Text=o.SelfName;showSelfAsYou.IsChecked=o.ShowSelfAsYou;pinSelfFirst.IsChecked=o.PinSelfFirst;colorHex=o.Color;damageHex=o.DamageColor;healerHex=o.HealerColor;tankHex=o.TankColor;roleColors.IsChecked=o.RoleColors;autoHide.IsChecked=o.AutoHide;fade.IsChecked=o.Fade;smooth.IsChecked=o.Smooth;
        Swatch(color,colorHex);Swatch(damageColor,damageHex);Swatch(healerColor,healerHex);Swatch(tankColor,tankHex);damageColor.IsEnabled=healerColor.IsEnabled=tankColor.IsEnabled=o.RoleColors;
        numbers["Refresh"].Value=o.RefreshIntervalMs;numbers["Idle"].Value=o.IdleSeconds;numbers["Opacity"].Value=(decimal)(o.BackgroundOpacity*100.0/255);numbers["Rows"].Value=o.MaxRows;numbers["Width"].Value=o.Bounds.Width;numbers["Height"].Value=o.Bounds.Height;numbers["X"].Value=o.Bounds.X;numbers["Y"].Value=o.Bounds.Y;
        numbers["HideAfter"].Value=(decimal)o.HideAfterSeconds;numbers["Fade"].Value=(decimal)o.FadeSeconds;numbers["Smooth"].Value=(decimal)o.SmoothingSeconds;numbers["HideAfter"].IsEnabled=o.AutoHide;numbers["Fade"].IsEnabled=o.Fade;numbers["Smooth"].IsEnabled=o.Smooth;
        scroller.IsEnabled=previewCard.IsEnabled=o.Enabled;scroller.Opacity=previewCard.Opacity=o.Enabled?1:.4;numbers["Opacity"].IsEnabled=o.Background;using(var w=new DpsPaintWorkspace())using(var b=DpsDesign.Render(360,170,DpsDesign.Sample(o),o,false,owner.Language,w))preview.Source=SettingsVisual.Bitmap(b);UiLanguage.Apply(this,owner.Language);UpdateStatus();
    }finally{loading=false;}}
    internal void RenderSections(string folder){scroller.ScrollToVerticalOffset(540);SettingsVisual.RenderPreview(window,System.IO.Path.Combine(folder,"settings-dps-colors-es.png"));scroller.ScrollToVerticalOffset(1050);SettingsVisual.RenderPreview(window,System.IO.Path.Combine(folder,"settings-dps-animation-es.png"));scroller.ScrollToTop();}
    internal void VerifyHistory(){history.Verify();SelectHistory(true);if(history.Visibility!=Visibility.Visible||activation.Visibility!=Visibility.Collapsed)throw new Exception("History tab must replace configuration controls");SelectHistory(false);}
    internal void RenderHistoryDetails(string path){history.RenderDetails(path);}
    internal void VerifyIdentityOptions(){var original=owner.Configuration;var c=original.Copy();c.Dps.Enabled=true;c.Dps.ShowSelfAsYou=true;c.Dps.PinSelfFirst=true;owner.ApplyConfiguration(c);Reload();if(showSelfAsYou.IsChecked!=true||pinSelfFirst.IsChecked!=true)throw new Exception("Self display settings failed to reload");pinSelfFirst.IsChecked=false;Changed();if(owner.Configuration.Dps.PinSelfFirst||!owner.Configuration.Dps.ShowSelfAsYou)throw new Exception("Pin toggle must preserve name display option");owner.UndoConfiguration();if(!ConfigurationHistory.Same(c,owner.Configuration))throw new Exception("Self display undo failed");owner.RedoConfiguration();if(owner.Configuration.Dps.PinSelfFirst)throw new Exception("Self display redo failed");owner.ApplyConfiguration(original);Reload();}
    internal void VerifyCombatView(){var original=owner.Configuration;var c=original.Copy();c.Dps.Enabled=true;c.Dps.View="healing";owner.ApplyConfiguration(c);Reload();if(view.SelectedIndex!=1)throw new Exception("Healing view did not reload");view.SelectedIndex=2;Reload();if(owner.Configuration.Dps.View!="received")throw new Exception("Received view did not apply");owner.UndoConfiguration();Reload();if(view.SelectedIndex!=1||!ConfigurationHistory.Same(c,owner.Configuration))throw new Exception("Combat view undo must preserve other modules");owner.RedoConfiguration();Reload();if(view.SelectedIndex!=2)throw new Exception("Combat view redo failed");owner.ApplyConfiguration(original);Reload();}
    internal void Verify(){var original=owner.Configuration;var c=original.Copy();c.Dps.Enabled=true;c.Dps.Scope="party";c.Dps.Color="#123456";c.Dps.DamageColor="#DD1122";c.Dps.HealerColor="#22BB44";c.Dps.TankColor="#3355CC";c.Dps.AutoHide=true;c.Dps.HideAfterSeconds=30;c.Dps.SmoothingSeconds=.27;c.Dps.RefreshIntervalMs=1000;owner.ApplyConfiguration(c);Reload();if(!scroller.IsEnabled||scope.SelectedIndex!=1||colorHex!="#123456"||numbers["Refresh"].Value!=1000||damageHex!="#DD1122"||healerHex!="#22BB44"||tankHex!="#3355CC"||numbers["Smooth"].Value!=.27M||numbers["HideAfter"].Value!=30)throw new Exception("DPS settings failed to reload");owner.UndoConfiguration();if(!ConfigurationHistory.Same(original,owner.Configuration))throw new Exception("DPS undo changes other modules");owner.RedoConfiguration();if(!ConfigurationHistory.Same(c,owner.Configuration))throw new Exception("DPS redo failed");numbers["Smooth"].Value=.32M;Changed();if(owner.Configuration.Dps.SmoothingSeconds!=.32)throw new Exception("DPS animation settings did not apply");owner.UndoConfiguration();if(!ConfigurationHistory.Same(c,owner.Configuration))throw new Exception("Animation undo must restore all settings");c.Dps.Enabled=false;owner.ApplyConfiguration(c);Reload();if(scroller.IsEnabled||!enabled.IsEnabled)throw new Exception("Disabled DPS controls must be disabled except activation");owner.ApplyConfiguration(original);}
}
