using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Text;
using System.Web.Script.Serialization;

internal static class DpsVerification {
    static void Check(bool value,string message){if(!value)throw new Exception(message);}
    static void V(List<byte> b,uint v){while(v>=128){b.Add((byte)((v&127)|128));v>>=7;}b.Add((byte)v);}
    static byte[] Hit(uint source,uint amount,bool extras,uint target=99){var b=new List<byte>(new byte[]{4,0x38});V(b,target);V(b,extras?38u:6u);V(b,0);V(b,source);b.AddRange(BitConverter.GetBytes(15210000));b.Add(1);V(b,2);b.AddRange(new byte[]{128,0,1,85,102,119,136,1,0,0,0});V(b,10817);V(b,amount);if(extras){V(b,2);V(b,11);V(b,11);}b.AddRange(new byte[]{1,0});return b.ToArray();}
    static byte[] Identity(uint actor,string name){var b=new List<byte>(new byte[]{4,0x8d,1,0,0,0,0});V(b,actor);b.AddRange(new byte[]{1,0,(byte)name.Length});b.AddRange(Encoding.UTF8.GetBytes(name));return b.ToArray();}
    static byte[] Energy(uint actor){var b=new List<byte>(new byte[]{0,0x8d});V(b,actor);b.AddRange(new byte[]{1,1,3});b.AddRange(BitConverter.GetBytes(1000));return b.ToArray();}
    static byte[] Spawn(uint actor,uint parent){var b=new List<byte>(new byte[]{0x41,0x36});V(b,actor);b.AddRange(new byte[]{31,0,0});b.AddRange(BitConverter.GetBytes(2920551));b.AddRange(BitConverter.GetBytes((ushort)576));b.AddRange(new byte[19]);V(b,1000);V(b,1000);b.AddRange(new byte[54]);V(b,1);b.Add(17);V(b,1);b.AddRange(BitConverter.GetBytes(1));b.AddRange(new byte[16]);V(b,actor);b.AddRange(new byte[]{1,2});b.AddRange(new byte[15]);b.AddRange(BitConverter.GetBytes(parent));V(b,2);b.AddRange(new byte[16]);V(b,0);return b.ToArray();}
    static byte[] Tick(uint source,byte flags,uint skill,uint amount){var b=new List<byte>(new byte[]{5,0x38});V(b,99);b.Add(flags);V(b,source);V(b,1);b.AddRange(BitConverter.GetBytes(1539000011));if((flags&1)!=0)V(b,1000);if((flags&2)!=0)V(b,amount);if((flags&8)!=0)b.AddRange(BitConverter.GetBytes(skill));return b.ToArray();}
    static byte[] Member(uint actor,string name,uint code=26){var b=new List<byte>();b.AddRange(BitConverter.GetBytes(actor));b.AddRange(BitConverter.GetBytes((ushort)1301));b.AddRange(BitConverter.GetBytes((ushort)1301));b.Add(36);b.AddRange(Encoding.ASCII.GetBytes("00000000-0000-0000-0000-000000000000"));b.AddRange(new byte[6]);b.AddRange(BitConverter.GetBytes((ushort)1301));b.Add((byte)name.Length);b.AddRange(Encoding.UTF8.GetBytes(name));b.AddRange(BitConverter.GetBytes(code));b.AddRange(new byte[12]);return b.ToArray();}
    static byte[] Party(bool friend){var b=new List<byte>(new byte[]{0,0x92,8});b.AddRange(Member(42,"Alpha"));if(friend)b.AddRange(Member(43,"Beta",33));return b.ToArray();}
    static byte[] Vital(uint actor){var b=new List<byte>(new byte[]{0x1b,0x92});V(b,actor);V(b,9000);V(b,10000);b.AddRange(BitConverter.GetBytes(2000u));b.AddRange(BitConverter.GetBytes(3000u));b.AddRange(new byte[16]);b.Add(1);return b.ToArray();}
    static byte[] Npc(uint actor){var b=new List<byte>(new byte[]{0x41,0x36});V(b,actor);b.AddRange(new byte[]{0,0,0,1,0,0,0});return b.ToArray();}
    static void Feed(DpsSignal signal,byte[] frame,double ts){signal.Consume(frame,0,frame.Length,ts,"test-stream");}
    internal static void Run(string root){
        DpsSignal.Hit e;byte[] hit=Hit(42,1263,true);Check(DpsSignal.Direct(hit,0,hit.Length,out e)&&e.Amount==1263&&e.Extras==2,"Included additional impacts must not be added twice");
        for(int end=0;end<hit.Length-2;end++)Check(!DpsSignal.Direct(hit,0,end,out e),"Truncated hit must fail closed");
        byte[] tick=Tick(98,10,15390002,194);Check(DpsSignal.Periodic(tick,0,tick.Length,out e)&&e.Amount==194,"Fire Wall current impact");
        byte[] heal=Tick(98,11,2011101,420);Check(!DpsSignal.Periodic(heal,0,heal.Length,out e),"Potion remaining and healing must never enter DPS");
        for(int end=0;end<tick.Length;end++)Check(!DpsSignal.Periodic(tick,0,end,out e),"Truncated periodic impact");
        uint actor,parent;byte[] spawn=Spawn(98,42);Check(DpsSignal.EffectParent(spawn,0,spawn.Length,out actor,out parent)&&actor==98&&parent==42,"Explicit effect parent");
        for(int end=0;end<spawn.Length;end++)Check(!DpsSignal.EffectParent(spawn,0,end,out actor,out parent),"Partial spawn must not give a parent");
        var signal=new DpsSignal();var o=new DpsOptions{Enabled=true,Scope="global"};signal.Configure(o);Feed(signal,Energy(42),1);Feed(signal,Identity(42,"Alpha"),1);Feed(signal,Identity(43,"Beta"),1);
        var npc=new List<byte>(new byte[]{0x41,0x36});V(npc,99);npc.AddRange(new byte[]{0,0,0,1,0,0,0});Feed(signal,npc.ToArray(),1);Feed(signal,spawn,1);
        Feed(signal,Hit(98,1263,true),2);Feed(signal,Hit(43,400,false),3);Feed(signal,tick,4);Feed(signal,heal,4);
        var s=signal.Read(4);Check(s.Rows.Count==2&&s.Rows[0].Damage==1457&&s.Rows[0].Hits==4,"Supported DoT is automatic and effect ownership remains attributed");
        double shared=s.Duration;o.Scope="self";signal.Configure(o);s=signal.Read(4);Check(s.Rows.Count==1&&s.Rows[0].Name=="Alpha"&&s.Duration==shared&&s.LastImpact==4,"Self filter retains duration, uses its own activity for hiding");
        Feed(signal,Hit(99,100,false,42),4);s=signal.Read(4);Check(s.LastImpact==4&&s.Rows[0].Damage==1457,"Incoming attacks keep the selected player active without increasing DPS");
        o.Scope="party";signal.Configure(o);Feed(signal,Party(true),4);s=signal.Read(4);Check(s.PartyKnown&&s.Rows.Count==2&&s.Rows[1].Role==2,"Observed party join updates the class role");Feed(signal,Party(false),5);s=signal.Read(5);Check(s.Rows.Count==1,"Observed party leave replaces members");
        var delta=new List<byte>(new byte[]{0x0d,0x92,0,2});delta.AddRange(Member(43,"Beta",33));Feed(signal,delta.ToArray(),5.1);s=signal.Read(5.1);Check(s.PartyKnown&&s.Rows.Count==2,"Single-member join update must append to the party");
        Feed(signal,Party(false),5.2);Check(signal.Read(5.2).Rows.Count==1,"Full roster replaces a prior incremental join");
        o.Scope="global";signal.Configure(o);Check(signal.Read(5.2).Rows.Count==2,"Party filter must not erase global totals");
        signal.ResetEncounter();Feed(signal,tick,6);Check(signal.Read(6).Rows[0].Damage==194&&signal.Read(6).Rows[0].PeriodicDamage==194,"Manual reset clears totals and supported ticks resume without a setting");
        Feed(signal,heal,7);Check(signal.Read(7).Rows[0].Damage==194,"Healing must not change damage");Feed(signal,Hit(42,100,false),20);Check(signal.Read(20).Rows[0].Damage==100,"Idle gap starts new encounter");
        signal.ResetEncounter();Check(signal.Read(20).Rows.Count==0,"Manual reset");Feed(signal,Hit(98,200,false),130);Check(signal.Read(130).Rows.Count==0,"Stale entities expire after traffic gap");
        var random=new Random(31);for(int n=0;n<10000;n++){var bytes=new byte[random.Next(0,140)];random.NextBytes(bytes);DpsSignal.Direct(bytes,0,bytes.Length,out e);DpsSignal.Periodic(bytes,0,bytes.Length,out e);DpsSignal.EffectParent(bytes,0,bytes.Length,out actor,out parent);signal.Consume(bytes,0,bytes.Length,200+n*.01,"test-stream");}
        var serializer=new JavaScriptSerializer();o.Color="#123456";o.Bounds=new Rectangle(20,30,400,250);var restored=DpsOptions.Read(serializer.Deserialize<Dictionary<string,object>>(serializer.Serialize(new{dps=o})));Check(DpsOptions.Same(o,restored)&&!DpsOptions.Read(new Dictionary<string,object>()).Enabled,"Settings migration/persistence");
        VerifyTargetRecovery();VerifyHitTags();VerifyCombatMetrics();VerifyHistory(root);VerifyIndividualDeletion(root);VerifyMinimumDuration(root);VerifyPartyRecovery();VerifyDungeonTransition();VerifySelfDisplay();VerifyMotion();Check(DpsSignal.RoleFromWire(9)==3&&DpsSignal.RoleFromWire(26)==1&&DpsSignal.RoleFromWire(33)==2&&DpsSignal.RoleFromWire(999)==0,"Wire role mapping");
        string designs=Path.Combine(root,"designs");Directory.CreateDirectory(designs);using(var w=new DpsPaintWorkspace()){
            using(var b=DpsDesign.Render(380,220,DpsDesign.Sample(),new DpsOptions(),false,"en",w)){Check(b.GetPixel(0,0).A==0&&b.GetPixel(20,20).A>0,"Transparent rounded panel");b.Save(Path.Combine(designs,"dps-widget-en.png"));}
            using(var b=DpsDesign.Render(380,220,DpsDesign.Sample(),new DpsOptions(),false,"es",w))b.Save(Path.Combine(designs,"dps-widget-es.png"));
            foreach(string view in new[]{"damage","healing","received"}){var metrics=new DpsOptions{View=view};using(var b=DpsDesign.Render(578,241,DpsDesign.Sample(metrics),metrics,false,"es",w))b.Save(Path.Combine(designs,"dps-metrics-"+view+"-es.png"));using(var b=DpsDesign.Render(260,220,DpsDesign.Sample(metrics),metrics,false,"en",w))b.Save(Path.Combine(designs,"dps-metrics-"+view+"-small.png"));}
            var five=DpsDesign.Sample();five.Rows.Add(new DpsSignal.Row{Actor=4,Name="Player Four",Role=1,Damage=15000,Dps=600});five.Rows.Add(new DpsSignal.Row{Actor=5,Name="Player Five",Role=3,Damage=10000,Dps=400});foreach(var size in new[]{new Size(578,241),new Size(260,110)})using(var b=DpsDesign.Render(size.Width,size.Height,five,new DpsOptions(),false,"es",w)){int header=DpsDesign.HeaderHeight(size.Width),footer=DpsDesign.FooterHeight(size.Width,size.Height),line=Math.Max(21,(size.Height-header-footer)/6),row=size.Height==110?1:5;Check(b.GetPixel(20,header+(row+1)*line-3).ToArgb()==ColorTranslator.FromHtml(row==5?"#4A92E4":"#E05252").ToArgb(),"Tabs must preserve rows at "+size+" pixel="+b.GetPixel(20,header+(row+1)*line-3));b.Save(Path.Combine(designs,"dps-tabs-"+size.Width+"x"+size.Height+"-es.png"));}
            using(var b=DpsDesign.Render(380,220,new DpsSignal.Snapshot{NeedsIdentification=true,Status="Dash once to identify your character"},new DpsOptions(),false,"es",w))b.Save(Path.Combine(designs,"dps-detection-es.png"));
            var personal=new DpsOptions{ShowSelfAsYou=true,PinSelfFirst=true};using(var b=DpsDesign.Render(380,220,DpsDesign.Sample(personal),personal,false,"es",w))b.Save(Path.Combine(designs,"dps-self-first-es.png"));
            var sample=DpsDesign.Sample();var style=new DpsOptions();w.ReplacePanel(DpsDesign.Render(380,220,sample,style,false,"en",w,null,false));int barY=DpsDesign.HeaderHeight(380)+2*((220-DpsDesign.HeaderHeight(380)-25)/(style.MaxRows+1))-3;Color empty=w.Panel.GetPixel(20,barY);var ratios=new Dictionary<uint,double>{{1,.5},{2,.25},{3,.1}};using(var b=DpsDesign.Compose(w,sample,style,ratios)){Check(b.GetPixel(20,barY).ToArgb()==ColorTranslator.FromHtml(style.DamageColor).ToArgb()&&b.GetPixel(300,barY).ToArgb()==w.Panel.GetPixel(300,barY).ToArgb()&&w.Panel.GetPixel(20,barY).ToArgb()==empty.ToArgb(),"Animated bars reuse an unchanged text/background panel");}
        }
        var palette=new DpsOptions{DamageColor="#CC1122",HealerColor="#22AA33",TankColor="#3344BB"};Check(DpsDesign.RowColor(new DpsSignal.Row{Role=1},palette)==ColorTranslator.FromHtml(palette.DamageColor)&&DpsDesign.RowColor(new DpsSignal.Row{Role=2},palette)==ColorTranslator.FromHtml(palette.HealerColor)&&DpsDesign.RowColor(new DpsSignal.Row{Role=3},palette)==ColorTranslator.FromHtml(palette.TankColor),"Custom role palette");palette.RoleColors=false;Check(DpsDesign.RowColor(new DpsSignal.Row{Role=3},palette)==ColorTranslator.FromHtml(palette.Color),"Disable role colors preserves custom fallback");
        Check(DpsDesign.Resize(new Rectangle(10,20,380,220),new Point(1000,1000),13)==new Rectangle(130,130,260,110),"Resize minimum preserves opposite corner");
        var area=new Rectangle(0,0,2560,1552);var fitted=DpsDesign.Constrain(new Rectangle(1615,1356,578,241),area);Check(area.Contains(fitted)&&fitted.Bottom==1552&&fitted.Width==578&&fitted.Height==241,"Unlocked DPS must leave the bottom taskbar accessible");area=new Rectangle(-1920,40,1880,1040);Check(area.Contains(DpsDesign.Constrain(new Rectangle(-300,-10,578,241),area)),"Taskbar boundary supports negative monitor positions and top/side taskbars");
        var screen=System.Windows.Forms.Screen.PrimaryScreen;File.WriteAllText(Path.Combine(root,"dps-workarea-test.txt"),"Screen: "+screen.Bounds+"; Working area: "+screen.WorkingArea+"; safe DPS: "+DpsDesign.UsableBounds(new Rectangle(screen.Bounds.Right-578,screen.Bounds.Bottom-241,578,241)));
        using(var owner=new EnergyOverlay(root,true)){using(var widget=new DpsOverlay(owner,new DpsSignal(),true)){widget.VerifyCache();widget.VerifyTabs();}var settings=new HelperSettings(owner);try{settings.VerifyDps(root);}finally{settings.Close();}var pane=new DpsSettingsPane(owner,null);pane.VerifyIdentityOptions();pane.VerifyCombatView();pane.VerifyHistory();}
        File.WriteAllText(Path.Combine(root,"dps-test.txt"),"PASS: captured Front/Back/Double/Perfect and combinations, variable restoration, metadata absence; per-player primary peak/ticks, immutable metrics and legacy unknowns; sixty-second history filter/boundaries/disable/persistence/no short-fight disk writes; damage parsing; explicit ownership; automatic identified DoT; healing done/received/self/HoT/HPS and exclusions; primary critical amount share versus observed frequency; no extra-impact/periodic crit guessing; legacy toggle migration; combat views/sorting/pinning/undo and native locked tabs; immutable per-player history; exactly-once idle/reset/transport completion; persistent/atomic saves; retention/oldest eviction; individual/all deletion; filtered localized TXT; history UI; scoped activity; party full/delta/deferred/startup recovery and expiry/leave; persistent dash notice; localized self display; wire roles/custom colors; fade reversal/idle hide/unlocked visibility; smooth growth/shrink and disable; reset/expiry; malformed inputs; persistence; resize; EN/ES UI; disabled controls; render/resource cache.");
    }
    static byte[] MetricHit(uint source,uint target,uint amount,uint skill,bool critical,bool extras=false,byte tags=128,byte position=1,uint restoration=0,bool metadata=true){var b=new List<byte>(new byte[]{4,0x38});V(b,target);V(b,(extras?36u:4u)|(metadata?2u:0u));V(b,0);V(b,source);b.AddRange(BitConverter.GetBytes(skill));b.Add(1);V(b,critical?3u:2u);if(metadata){b.Add(tags);V(b,restoration);b.Add(position);}b.AddRange(new byte[]{85,102,119,136,1,0,0,0});V(b,10817);V(b,amount);if(extras){V(b,2);V(b,11);V(b,11);}b.AddRange(new byte[]{1,0});return b.ToArray();}
    static byte[] MetricTick(uint source,uint target,uint amount,uint skill,uint effect,byte flags=10){var b=new List<byte>(new byte[]{5,0x38});V(b,target);b.Add(flags);V(b,source);V(b,1);b.AddRange(BitConverter.GetBytes(effect));if((flags&1)!=0)V(b,9999);if((flags&2)!=0)V(b,amount);if((flags&8)!=0)b.AddRange(BitConverter.GetBytes(skill));return b.ToArray();}
    static DpsSignal.Row Find(DpsSignal.Snapshot s,uint actor){foreach(var row in s.Rows)if(row.Actor==actor)return row;throw new Exception("Missing metrics actor");}
    internal static DpsHistoryRecord HistorySample(double timestamp,double duration=24.5){var s=DpsDesign.Sample();var r=new DpsHistoryRecord{Id=Guid.NewGuid().ToString("N"),Started=timestamp-duration,Ended=timestamp,Duration=duration,Reason="Inactivity",Scope="party",SelfActor=2,Map=600021,PartyKnown=true,Party=new List<uint>{1,2,3}};foreach(var p in s.Rows)r.Players.Add(DpsHistoryPlayer.Capture(p,p.Name,p.Role,r.Duration));return r;}
    static byte[] Hex(string value){var result=new byte[value.Length/2];for(int i=0;i<result.Length;i++)result[i]=Convert.ToByte(value.Substring(i*2,2),16);return result;}
    static byte[] TargetHp(uint actor,long hp){var b=new List<byte>(new byte[]{0,0x8d});V(b,actor);b.AddRange(new byte[]{2,1,0});b.AddRange(BitConverter.GetBytes(hp));return b.ToArray();}
    static void VerifyTargetRecovery(){
        var signal=new DpsSignal();signal.Configure(new DpsOptions{Enabled=true,Scope="self"});Feed(signal,Energy(42),1);
        Feed(signal,TargetHp(99,10000),2);Feed(signal,MetricHit(42,99,100,15210000,false,position:2),2.1);
        Check(signal.Read(2.1).Rows.Count==0,"Unknown target needs subsequent HP evidence");Feed(signal,TargetHp(99,9550),2.1);
        Check(Find(signal.Read(2.1),42).Damage==100&&signal.Read(2.1).Npcs==0&&signal.Read(2.1).RecoveredImpacts==1,"Restart recovery retains announced damage without inventing NPC identity or HP scaling");
        Feed(signal,MetricHit(42,99,150,15210000,false,position:1),2.2);Feed(signal,TargetHp(99,9600),2.2);Check(Find(signal.Read(2.2),42).Damage==100,"Healing HP increases cannot confirm damage");
        Feed(signal,MetricHit(42,99,200,15210000,false,metadata:false),2.3);Feed(signal,TargetHp(99,9000),2.3);Check(Find(signal.Read(2.3),42).Damage==100,"Untagged unknown effects cannot confirm damage");
        Feed(signal,MetricHit(42,99,300,18120000,false,position:2),2.4);Feed(signal,TargetHp(99,8000),2.4);Check(Find(signal.Read(2.4),42).Damage==100,"Known heals remain excluded from recovery");
        Feed(signal,MetricHit(42,99,400,15210000,false,position:2),3);Feed(signal,TargetHp(99,7000),3);Check(Find(signal.Read(3),42).Damage==100,"Stale target HP cannot confirm damage");
        Feed(signal,Identity(99,"Beta"),3.1);Feed(signal,TargetHp(99,6000),3.2);Feed(signal,MetricHit(42,99,500,15210000,false,position:2),3.3);Feed(signal,TargetHp(99,5000),3.3);Check(Find(signal.Read(3.3),42).Damage==100,"Player identity invalidates target recovery");
        signal.ResetTransport();Feed(signal,Energy(42),4);Feed(signal,MetricHit(42,99,600,15210000,false,position:2),4.1);Feed(signal,TargetHp(99,4000),4.1);Check(signal.Read(4.1).Rows.Count==0,"Flow reset removes recovery evidence");
        var smallDrop=new DpsSignal();smallDrop.Configure(new DpsOptions{Enabled=true,Scope="self"});Feed(smallDrop,Energy(42),1);Feed(smallDrop,TargetHp(99,1000),2);Feed(smallDrop,MetricHit(42,99,500,15210000,false),2.1);Feed(smallDrop,TargetHp(99,999),2.1);Check(smallDrop.Read(2.1).Rows.Count==0,"Unrelated small HP drop cannot confirm large impact");
    }
    static void VerifyHitTags(){
        DpsSignal.Hit decoded;var real=Hex("0438CED1013600D805E4D012015C038800021B99596B010000009E55E52404D603D603D603D6030100");
        Check(DpsSignal.Direct(real,0,real.Length,out decoded)&&decoded.TagsKnown&&decoded.Position==2&&decoded.Double&&!decoded.Perfect&&decoded.Critical&&decoded.Amount==4709&&decoded.PrimaryAmount==2829,"Captured Front Double Critical retains its original amounts");
        real=Hex("0438CED1013600D805E4D0120171038400010D20596B020000009E55F21103E501E501E5010200");
        Check(DpsSignal.Direct(real,0,real.Length,out decoded)&&decoded.TagsKnown&&decoded.Position==1&&decoded.Perfect&&!decoded.Double&&decoded.Critical,"Captured Back Perfect Critical metadata");
        var variable=MetricHit(42,99,1000,15210000,true,false,12,2,16384);Check(DpsSignal.Direct(variable,0,variable.Length,out decoded)&&decoded.TagsKnown&&decoded.Double&&decoded.Perfect&&decoded.Position==2,"Restoration varint length must not shift hit tags");
        var unknown=MetricHit(42,99,900,15210000,false,false,4,7);Check(DpsSignal.Direct(unknown,0,unknown.Length,out decoded)&&!decoded.TagsKnown&&decoded.Amount==900,"Unknown position keeps damage without fabricated tags");
        var missing=MetricHit(42,99,800,15210000,false,false,0,0,0,false);Check(DpsSignal.Direct(missing,0,missing.Length,out decoded)&&!decoded.TagsKnown&&decoded.Amount==800,"Absent plotter is unavailable rather than a zero positional count");
        for(int end=0;end<variable.Length-2;end++)Check(!DpsSignal.Direct(variable,0,end,out decoded),"Truncated tagged damage fails closed");
        var reader=new DpsSignal();reader.Configure(new DpsOptions{Enabled=true,Scope="global"});Feed(reader,Energy(42),1);Feed(reader,Identity(42,"Alpha"),1);Feed(reader,Identity(43,"Beta"),1);Feed(reader,Npc(99),1);
        Feed(reader,MetricHit(42,99,1000,15210000,true,false,8,1),2);Feed(reader,MetricHit(42,99,300,15210000,false,false,4,2),3);Feed(reader,MetricHit(42,99,700,15210000,true,false,4,1),4);Feed(reader,MetricHit(42,99,500,15210000,false,false,8,0),5);Feed(reader,unknown,6);Feed(reader,missing,7);
        var row=Find(reader.Read(7),42);Check(row.Damage==4200&&row.HighestHit==1000&&row.TaggedDamageEvents==4&&row.BackHits==2&&row.FrontHits==1&&row.DoubleHits==2&&row.PerfectHits==2&&row.BackCriticalHits==2&&row.BackDoubleCriticalHits==1&&row.BackPerfectHits==1&&row.FrontPerfectHits==1,"Per-player overlapping tag counts must exclude missing/unknown metadata");
        Feed(reader,MetricHit(43,99,250,15210000,true,false,8,2),7.1);Check(Find(reader.Read(7.1),43).FrontDoubleCriticalHits==1&&Find(reader.Read(7.1),42).FrontDoubleCriticalHits==0,"Highest hit and combos are isolated per player");
        Feed(reader,MetricHit(42,99,2000,15210000,false,true,0,0),8);Check(Find(reader.Read(8),42).HighestHit==1978,"Largest primary hit must not include the summed extra impacts");Feed(reader,Tick(42,10,15390002,5000),9);Feed(reader,MetricHit(43,42,90000,18160002,true),9.1);row=Find(reader.Read(9.1),42);Check(row.HighestHit==5000&&row.TaggedDamageEvents==5,"Periodic tick contributes once to highest hit; healing does not add damage or tags");
        var archived=DpsHistoryPlayer.Capture(row,"Alpha",1,8);row.HighestHit=1;row.BackHits=100;Check(archived.HighestHit==5000&&archived.BackHits==2,"Archived peak and tags are immutable snapshots");reader.ResetEncounter();Check(reader.Read(10).Rows.Count==0,"Reset discards peak and combo counters");
    }
    static void VerifyMinimumDuration(string root){
        var o=new DpsOptions{Enabled=true};Check(o.HistoryMinimumSeconds==60,"Default minimum fight duration must be sixty seconds");var json=new JavaScriptSerializer();var migrated=DpsOptions.Read(json.Deserialize<Dictionary<string,object>>("{\"dps\":{\"Enabled\":true,\"HistoryMaxRecords\":12}}"));Check(migrated.HistoryMinimumSeconds==60&&migrated.HistoryMaxRecords==12,"Existing preferences migrate without losing their storage limit");o.HistoryMinimumSeconds=-1;o.Normalize();Check(o.HistoryMinimumSeconds==0,"Minimum duration can be disabled and cannot be negative");o.HistoryMinimumSeconds=99999;o.Normalize();Check(o.HistoryMinimumSeconds==3600,"Minimum duration is bounded");o.HistoryMinimumSeconds=60;
        double now=DpsHistory.UtcNow();string folder=Path.Combine(root,"history-duration-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(folder);string path=Path.Combine(folder,"combat-history.json");
        using(var store=new DpsHistory(folder,o)){store.Add(HistorySample(now,59.999));Check(store.Read().Count==0&&store.Revision==0&&!File.Exists(path),"Short fights must not cause history changes or disk writes");store.Add(HistorySample(now,60));Check(store.Read().Count==1,"Exactly sixty seconds is accepted");o.HistoryMinimumSeconds=90;store.Configure(o);store.Add(HistorySample(now+1,80));Check(store.Read().Count==1,"Changing minimum only filters future records");o.HistoryMinimumSeconds=0;store.Configure(o);store.Add(HistorySample(now+2,0));Check(store.Read().Count==2,"Zero seconds saves an instantaneous fight");store.Flush();}
        o.HistoryMinimumSeconds=60;using(var store=new DpsHistory(folder,o)){Check(store.Read().Count==2&&store.Read()[1].Players[0].HighestHit.HasValue&&store.Read()[1].Players[0].BackHits.HasValue,"Peak and tag metrics persist; existing short records are retained");string text=DpsHistory.Text(store.Read()[1],"es");Check(text.Contains("Golpe más alto")&&text.Contains("Espalda doble crítico")&&text.Contains("Frente perfecto"),"TXT exports localized peak and all combinations");}
        var legacy=HistorySample(now,2);foreach(var player in legacy.Players){player.HighestHit=null;player.TaggedDamageEvents=player.BackHits=player.FrontHits=player.DoubleHits=player.PerfectHits=player.BackCriticalHits=player.FrontCriticalHits=player.BackDoubleCriticalHits=player.FrontDoubleCriticalHits=player.BackPerfectHits=player.FrontPerfectHits=null;}File.WriteAllText(path,json.Serialize(new{Version=1,Records=new[]{legacy}}));
        using(var store=new DpsHistory(folder,o)){Check(store.Read().Count==1&&store.Read()[0].Players[0].HighestHit==null&&store.Read()[0].Players[0].BackHits==null&&store.Error==null,"Older histories keep unknown metrics unavailable");Check(DpsHistory.Text(store.Read()[0],"en").Contains("—"),"Legacy exports must not invent peak or zero tags");}
        var saved=DpsOptions.Read(json.Deserialize<Dictionary<string,object>>(json.Serialize(new{dps=o})));Check(DpsOptions.Same(o,saved)&&saved.HistoryMinimumSeconds==60,"Minimum duration survives persistence");
    }
    static void VerifyIndividualDeletion(string root){
        var o=new DpsOptions{Enabled=true,HistoryMinimumSeconds=0};string folder=Path.Combine(root,"history-delete-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(folder);double now=DpsHistory.UtcNow();var first=HistorySample(now);var second=HistorySample(now+1);
        using(var store=new DpsHistory(folder,o)){store.Add(first);store.Add(second);Check(store.DeletePlayer(first.Id,2)&&!store.DeletePlayer(first.Id,2),"Player removal is scoped to one fight and idempotent");var rows=store.Read();Check(rows.Count==2&&rows[0].Players.Count==3&&rows[1].Players.Count==2&&first.Players.Count==3,"Player deletion preserves other fights and prior immutable snapshots");Check(store.Delete(second.Id)&&store.Read().Count==1&&store.Read()[0].Id==first.Id,"Whole-fight deletion does not remove another record");Check(store.Flush(),"Targeted deletions persist");}
        using(var store=new DpsHistory(folder,o)){var rows=store.Read();Check(rows.Count==1&&rows[0].Id==first.Id&&rows[0].Players.Count==2,"Fight and player deletion persist across restart");Check(store.DeletePlayer(first.Id,1)&&store.DeletePlayer(first.Id,3)&&store.Read().Count==0,"Deleting the last player removes the empty fight");Check(!store.DeletePlayer("missing",1)&&!store.DeletePlayer(first.Id,0),"Unknown IDs are harmless");}
    }
    static void VerifyHistory(string root){
        double now=DpsHistory.UtcNow();var reader=new DpsSignal();var o=new DpsOptions{Enabled=true,Scope="self",IdleSeconds=5};var completed=new List<DpsHistoryRecord>();reader.Configure(o);reader.EncounterCompleted=completed.Add;Feed(reader,Energy(42),now);Feed(reader,Party(true),now);Feed(reader,Npc(99),now);Feed(reader,Hit(43,300,false),now+1);Feed(reader,MetricHit(42,99,100,15210000,true),now+2);Feed(reader,Tick(42,10,15390002,194),now+3);Feed(reader,MetricHit(43,42,200,18160002,false),now+4);reader.Read(now+8);Check(completed.Count==0,"An active fight must not be archived early");reader.Read(now+9);reader.Read(now+9);Check(completed.Count==1&&completed[0].Players.Count==2&&completed[0].SelfActor==42&&completed[0].Party.Count==2&&completed[0].Duration==3,"Idle completion archives all players once independently of the widget filter");var first=completed[0];Check(first.Players[1].Actor==42&&first.Players[1].Damage==294&&first.Players[1].PeriodicDamage==194&&first.Players[1].HealingReceived==200&&first.Players[1].DamageCritRate==100,"Archived rows retain damage, DoT, healing and critical denominators");Feed(reader,Hit(42,80,false),now+10);reader.ResetEncounter();reader.ResetEncounter();Check(completed.Count==2&&completed[1].Reason=="Manual reset"&&first.Players[1].Damage==294,"New encounter and reset cannot mutate or duplicate an archived fight");Feed(reader,Hit(42,90,false),now+11);reader.ResetTransport();Check(completed.Count==3&&completed[2].Players[0].Name=="Alpha"&&completed[2].Party.Count==2,"Connection reset preserves identity before clearing entities");
        reader=new DpsSignal();o.Scope="global";reader.Configure(o);reader.EncounterCompleted=completed.Add;Feed(reader,Energy(42),now);Feed(reader,Npc(99),now);for(uint id=42;id<55;id++){Feed(reader,Identity(id,"Player"+id),now);Feed(reader,Hit(id,100,false),now+1);}reader.ResetEncounter();Check(completed[3].Players.Count==13,"History must not inherit the widget ten-row trim");
        string folder=Path.Combine(root,"history-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(folder);o.HistoryMinimumSeconds=0;o.HistoryMaxRecords=3;using(var store=new DpsHistory(folder,o)){for(int i=0;i<5;i++)store.Add(HistorySample(now+i));Check(store.Read().Count==3&&store.Read()[0].Ended==now+4&&store.Read()[2].Ended==now+2,"Maximum records evicts the oldest fight");Check(store.Flush()&&store.Error==null,"History writes asynchronously without errors");}using(var store=new DpsHistory(folder,o)){Check(store.Read().Count==3&&store.Read()[0].Players[1].Healing==43000&&store.Read()[0].Players[1].HealingCritRate.HasValue,"History persists and reloads every raw and derived metric");o.HistoryAutoDelete=true;o.HistoryAge=1;o.HistoryAgeUnit="hours";store.Configure(o);store.Add(HistorySample(now-7200));Check(store.Read().Count==3,"Enabled age cleanup removes an old fight");o.HistoryMaxRecords=10;o.HistoryAutoDelete=false;store.Configure(o);store.Add(HistorySample(now-7200));store.Maintain(now+1);Check(store.Read().Count==4,"Disabled age cleanup retains old records");o.HistoryAutoDelete=true;store.Configure(o);Check(store.Read().Count==3,"Turning age cleanup on prunes immediately");string id=store.Read()[1].Id;Check(store.Delete(id)&&!store.Delete(id)&&store.Read().Count==2,"Individual history deletion");var record=store.Read()[0];string text=DpsHistory.Text(record,"es");Check(text.Contains("Curación realizada")&&text.Contains("Daño periódico")&&text.Contains("crít."),"Localized TXT export includes combat metrics");string export=Path.Combine(folder,"export.txt");File.WriteAllText(export,text,Encoding.UTF8);Check(File.ReadAllText(export).Contains("Player Two")&&text.Split('\t').Length>29,"Exported TXT retains all player rows and columns");store.Clear();store.Flush();Check(store.Read().Count==0,"Clear all history");}using(var store=new DpsHistory(folder,o))Check(store.Read().Count==0,"Deleted histories must stay deleted after reopening");File.WriteAllText(Path.Combine(folder,"combat-history.json"),"invalid json");using(var store=new DpsHistory(folder,o)){Check(store.Read().Count==0&&Directory.GetFiles(folder,"combat-history.corrupt-*.json").Length==1,"Corrupt history must be preserved rather than crash or overwrite");store.Add(HistorySample(now));Check(store.Flush()&&store.Error==null,"New history can be stored after safe corruption backup");}
        var json=new JavaScriptSerializer();o.HistoryAutoDelete=true;o.HistoryAge=48;o.HistoryAgeUnit="hours";o.HistoryMaxRecords=20;var restored=DpsOptions.Read(json.Deserialize<Dictionary<string,object>>(json.Serialize(new{dps=o})));Check(DpsOptions.Same(o,restored),"History preferences survive settings persistence");
    }
    static void VerifyCombatMetrics(){
        var reader=new DpsSignal();var options=new DpsOptions{Enabled=true,Scope="global"};reader.Configure(options);Feed(reader,Energy(42),1);Feed(reader,Identity(42,"Alpha"),1);Feed(reader,Identity(43,"Beta"),1);Feed(reader,Npc(99),1);
        Feed(reader,MetricHit(42,99,100,15210000,false),2);Feed(reader,MetricHit(42,99,300,15210000,true,true),3);Feed(reader,Tick(42,10,15390002,194),4);
        var damage=Find(reader.Read(4),42);Check(damage.Damage==594&&damage.Hits==5&&damage.DamageEvents==2&&damage.DamagePrimary==378&&damage.DamageCritical==278,"Critical primary amounts exclude bundled extras; total damage includes supported DoT once");Check(DpsSignal.CriticalRate(damage,"damage")==50&&Math.Abs(DpsSignal.CriticalShare(damage,"damage").Value-100.0*278/378)<.0001,"Critical frequency and amount share are distinct, excluding periodic ticks");
        Feed(reader,MetricHit(43,42,800,18120000,false),5);Feed(reader,MetricHit(43,42,200,18120000,true,true),6);var hot=MetricTick(43,42,400,18120000,1812000011,11);Feed(reader,hot,7);
        var s=reader.Read(7);var healer=Find(s,43);var receiver=Find(s,42);Check(healer.Healing==1400&&receiver.HealingReceived==1400&&healer.Damage==0&&receiver.Damage==594,"Healing source/recipient totals include current HoT amount only and never enter damage");Check(healer.HealingEvents==2&&DpsSignal.CriticalRate(healer,"healing")==50&&healer.HealingPrimary==978&&healer.HealingCritical==178&&DpsSignal.CriticalShare(receiver,"received")==DpsSignal.CriticalShare(healer,"healing"),"Healing criticals exclude bundled extras and unflagged HoT; received metrics match source");Check(Math.Abs(healer.Hps-1400.0/5)<.0001,"HPS uses shared encounter duration");
        Feed(reader,MetricHit(43,43,200,18160002,false),7.1);s=reader.Read(7.1);Check(Find(s,43).Healing==1600&&Find(s,43).HealingReceived==200,"Self-heal counts once in each independent total");
        Feed(reader,MetricHit(99,42,900,18120000,true),7.2);Feed(reader,MetricTick(43,42,900,2011101,201110111,11),7.3);Feed(reader,MetricTick(43,42,900,17090000,1709000011,9),7.4);Feed(reader,MetricTick(43,42,900,12345678,1234567811),7.5);Check(Find(reader.Read(7.5),43).Healing==1600&&Find(reader.Read(7.5),42).HealingReceived==1400,"NPC/unknown/item/pending-only effects cannot become player healing");
        options.View="healing";reader.Configure(options);s=reader.Read(7.5);Check(s.Rows[0].Actor==43&&s.Rows[0].Healing==1600&&Find(s,42).Damage==594,"Switching to healing sorts without resetting retained damage");options.View="received";reader.Configure(options);Check(reader.Read(7.5).Rows[0].Actor==42,"Received view sorts recipients");options.PinSelfFirst=true;options.View="healing";reader.Configure(options);s=reader.Read(7.5);Check(s.Rows[0].Actor==42&&DpsDesign.MaximumTotal(s,"healing")==1600,"Pinning uses actual highest healing to normalize bars");
        DpsSignal.Hit hit;foreach(var pair in new[]{new uint[]{17070000,1707000011},new uint[]{17080000,1708000011},new uint[]{16140000,1614000011},new uint[]{17400000,1740000011},new uint[]{13730007,1373000712}}){var tick=MetricTick(43,99,300,pair[0],pair[1]);Check(DpsSignal.Periodic(tick,0,tick.Length,out hit)&&hit.Amount==300&&!hit.CriticalKnown,"Identified non-fire periodic families are accepted without inventing crit flags");for(int end=0;end<tick.Length;end++)Check(!DpsSignal.Periodic(tick,0,end,out hit),"Truncated periodic families must fail closed");var wrong=MetricTick(43,99,300,pair[0],pair[1]+1);Check(!DpsSignal.Periodic(wrong,0,wrong.Length,out hit),"Unknown effect suffix must remain excluded");}
        for(int end=0;end<hot.Length;end++)Check(!DpsSignal.HealingTick(hot,0,end,out hit),"Truncated healing tick must fail closed");Check(DpsDesign.Percent(DpsSignal.CriticalRate(new DpsSignal.Row(),"healing"))=="—","No eligible critical samples shows unavailable rather than zero");reader.ResetEncounter();Check(reader.Read(8).Rows.Count==0,"Reset clears all damage and healing metrics");
        var json=new JavaScriptSerializer();var legacy=DpsOptions.Read(json.Deserialize<Dictionary<string,object>>("{\"dps\":{\"Enabled\":true,\"CandidatePeriodic\":false}}"));Check(legacy.Enabled&&legacy.View=="damage","Legacy disabled experimental toggle migrates to automatic supported ticks");var persisted=DpsOptions.Read(json.Deserialize<Dictionary<string,object>>(json.Serialize(new{dps=options})));Check(persisted.View=="healing"&&DpsOptions.Same(options,persisted),"Combat view persists");
    }
    static void VerifySelfDisplay(){
        var defaults=new DpsOptions();Check(!defaults.ShowSelfAsYou&&!defaults.PinSelfFirst,"Self display options default off");var reader=new DpsSignal();var o=new DpsOptions{Enabled=true,Scope="global",Smooth=false};reader.Configure(o);Feed(reader,Energy(42),1);Feed(reader,Identity(42,"Alpha"),1);Feed(reader,Identity(43,"Beta"),1);Feed(reader,Identity(44,"You"),1);Feed(reader,Npc(99),1);Feed(reader,Hit(42,100,false),2);Feed(reader,Hit(43,1000,false),3);Feed(reader,Hit(44,500,false),4);
        var s=reader.Read(4);Check(s.Rows[0].Actor==43&&s.Rows[2].Actor==42,"Default keeps damage order");o.PinSelfFirst=true;o.ShowSelfAsYou=true;reader.Configure(o);s=reader.Read(4);Check(s.Rows[0].Actor==42&&s.Rows[0].Damage==100&&s.Rows[1].Actor==43&&s.Rows[2].Actor==44,"Pinning retains amounts and other player order");Check(DpsDesign.DisplayName(s.Rows[0],s,o,"es")=="Tú"&&DpsDesign.DisplayName(s.Rows[0],s,o,"en")=="You"&&s.Rows[0].Name=="Alpha","Self alias follows helper language without changing identity");Check(DpsDesign.DisplayName(s.Rows[2],s,o,"es")=="You","Actual other player names must not be translated");Check(DpsDesign.MaximumDamage(s)==1000,"Pinned first row must not be used as highest damage");var motion=new DpsMotion();motion.Set(s,o,0,4);motion.Step(0,false,o);Check(Math.Abs(motion.Ratios[42]-.1)<.00001&&motion.Ratios[43]==1,"Pinned bar proportions remain accurate");
        o.ShowSelfAsYou=false;o.PinSelfFirst=false;reader.Configure(o);s=reader.Read(4);Check(s.Rows[0].Actor==43&&DpsDesign.DisplayName(s.Rows[2],s,o,"es")=="Alpha","Disabling restores name and damage order");for(uint actor=50;actor<62;actor++){Feed(reader,Identity(actor,"Player"+actor),4.1);Feed(reader,Hit(actor,2000,false),4.2);}o.PinSelfFirst=true;reader.Configure(o);s=reader.Read(4.2);Check(s.Rows.Count==10&&s.Rows[0].Actor==42,"Pinned self survives visible result limit");
        o.ShowSelfAsYou=true;var json=new JavaScriptSerializer();var restored=DpsOptions.Read(json.Deserialize<Dictionary<string,object>>(json.Serialize(new{dps=o})));Check(restored.ShowSelfAsYou&&restored.PinSelfFirst&&DpsOptions.Same(o,restored),"Both self display options persist");
    }
    static byte[] Appearance(uint actor,string name,bool self,uint code){var b=new List<byte>(new byte[]{self?(byte)0x33:(byte)0x45,0x36});V(b,actor);b.AddRange(new byte[]{1,32,160,1,7});b.Add((byte)name.Length);b.AddRange(Encoding.UTF8.GetBytes(name));if(self)b.AddRange(new byte[]{21,5});b.AddRange(BitConverter.GetBytes(code));b.Add(1);b.AddRange(new byte[128]);return b.ToArray();}
    static void VerifyDungeonTransition(){
        var signal=new DpsSignal();signal.Configure(new DpsOptions{Enabled=true,Scope="party"});Feed(signal,Energy(42),1);Feed(signal,Identity(42,"OldSelf"),1);Feed(signal,Party(true),1);
        var roster=new List<byte>(new byte[]{0,0x92,8});foreach(var member in new[]{Member(50,"Alpha"),Member(51,"Beta",33)}){member[6]=0xf0;member[7]=0x10;roster.AddRange(member);}byte[] packet=roster.ToArray();signal.Consume(packet,0,packet.Length,2,"dungeon");Check(signal.Read(2).SelfActor==42&&signal.Read(2).PartyMembers==2,"Candidate flow cannot overwrite active party");
        var load=new byte[48];load[0]=0x21;load[1]=0x36;load[2]=1;load[6]=10;signal.Consume(load,0,load.Length,2.1,"dungeon");var self=Appearance(50,"Alpha",true,26);signal.Consume(self,0,self.Length,2.2,"dungeon");Check(signal.Read(2.2).SelfActor==50&&signal.Read(2.2).PartyMembers==2,"Instance roster before map load survives; origin may differ from realm");
        var friend=Appearance(52,"Gamma",false,14);uint id;string name;byte role;Check(DpsSignal.PlayerIdentity(friend,0,friend.Length,false,out id,out name,out role)&&id==52&&name=="Gamma"&&role==1,"Player appearance independently identifies class and name");for(int end=0;end<128;end++)Check(!DpsSignal.PlayerIdentity(friend,0,end,false,out id,out name,out role),"Truncated appearance cannot bind player");
        signal.Consume(friend,0,friend.Length,2.3,"dungeon");var vital=Vital(52);signal.Consume(vital,0,vital.Length,2.4,"dungeon");var npc=Npc(99);signal.Consume(npc,0,npc.Length,2.4,"dungeon");var hit=Hit(52,400,false);signal.Consume(hit,0,hit.Length,3,"dungeon");Check(signal.Read(3).PartyMembers==3&&signal.Read(3).Rows.Count==1&&signal.Read(3).Rows[0].Name=="Gamma","Late actor from appearance and party vitals recovers without rejoining");var energy=Energy(50);signal.Consume(energy,0,energy.Length,4,"dungeon");Check(signal.Read(4).Rows.Count==1&&signal.Read(4).PartyMembers==3,"First dash must preserve instance metadata and damage");Feed(signal,Identity(53,"Nearby"),4);Check(signal.Read(4).Players==3,"Old flow identity stays excluded");
        signal=new DpsSignal();signal.Configure(new DpsOptions{Enabled=true,Scope="party"});Feed(signal,Energy(42),1);signal.Consume(packet,0,packet.Length,2,"dungeon");signal.Consume(self,0,self.Length,2.2,"dungeon");Check(signal.Read(2.2).PartyMembers==2&&signal.Read(2.2).SelfActor==50,"SelfInfo selects new flow even when map load was missed");signal.ResetTransport();Check(signal.Read(3).NeedsIdentification,"Transport reset clears selected identity and staged roster");
        signal=new DpsSignal();signal.Configure(new DpsOptions{Enabled=true,Scope="party"});Feed(signal,load,1);Feed(signal,Appearance(42,"Alpha",true,26),1.1);Feed(signal,Party(true),1.2);Feed(signal,Npc(99),1.3);Feed(signal,Hit(42,100,false),2);load[2]=2;Feed(signal,load,3);Feed(signal,Appearance(42,"Alpha",true,26),3.1);Feed(signal,Hit(43,200,false),4);var retained=signal.Read(4);Check(retained.PartyMembers==2&&retained.Npcs==1&&retained.Rows.Count==2&&retained.Rows[1].Damage==100&&retained.Duration==2,"Same-map boss teleport retains NPC identity, party and encounter damage");load[6]=11;Feed(signal,load,5);Check(signal.Read(5).NeedsIdentification&&signal.Read(5).Npcs==0&&signal.Read(5).Rows.Count==0,"Confirmed map change still clears stale entities");
        var variant=Appearance(53,"Tank",false,8);variant[17]=2;Check(DpsSignal.PlayerIdentity(variant,0,variant.Length,false,out id,out name,out role)&&id==53&&name=="Tank"&&role==3,"All observed class variants including class 8 are accepted");
    }
    static void VerifyPartyRecovery(){
        var s=new DpsSignal();s.Configure(new DpsOptions{Enabled=true,Scope="party"});uint actor;byte[] vital=Vital(43);Check(DpsSignal.PartyVital(vital,0,vital.Length,out actor)&&actor==43,"Observed ongoing party vital envelope");for(int end=0;end<vital.Length;end++)Check(!DpsSignal.PartyVital(vital,0,end,out actor),"Truncated vital must not recover membership");
        Feed(s,vital,1);Feed(s,Identity(43,"Beta"),1.1);Feed(s,Identity(42,"Alpha"),1.1);Feed(s,Identity(44,"Gamma"),1.1);Feed(s,Npc(99),1.1);
        Feed(s,Hit(43,300,false),2);Check(s.Read(2).NeedsIdentification&&!s.Read(2).PartyKnown,"Telemetry before first dash stays pending");Feed(s,Energy(42),3);Feed(s,Hit(42,100,false),4);Feed(s,Hit(44,500,false),4.1);var snapshot=s.Read(4.1);Check(snapshot.PartyKnown&&!snapshot.NeedsIdentification&&snapshot.Rows.Count==2&&snapshot.Rows[0].Name=="Beta","Startup in existing party recovers friend, excludes nearby player");
        Feed(s,Vital(99),5);Check(s.Read(5).Rows.Count==2,"NPC vital cannot establish membership");Feed(s,Party(false),5.1);Check(s.Read(5.1).Rows.Count==1,"Full solo roster replaces recovered members immediately");
        Feed(s,Vital(43),6);Check(s.Read(6).Rows.Count==2,"Ongoing party member status repairs missing join");var leave=new byte[10];leave[0]=0x11;leave[1]=0x92;Feed(s,leave,7);Check(!s.Read(7).PartyKnown&&s.Read(7).Rows.Count==1,"Leave clears startup recovery without guessing an unknown database identity");
        Feed(s,Vital(43),8);Check(s.Read(8).PartyKnown,"Continued real membership can recover after reset");Check(!s.Read(129).PartyKnown&&s.Read(129).Rows.Count==1,"Unconfirmed membership expires rather than retaining departed players");s.ResetTransport();Check(s.Read(130).NeedsIdentification&&!s.Read(130).PartyKnown,"Transport reset clears all startup membership");
        s=new DpsSignal();s.Configure(new DpsOptions{Enabled=true,Scope="party"});Feed(s,Party(true),1);Feed(s,Energy(42),2);Feed(s,Npc(99),2);Feed(s,Hit(43,300,false),3);Check(s.Read(3).PartyKnown&&s.Read(3).Rows.Count==1&&s.Read(3).Rows[0].Name=="Beta","Full roster received before energy must be retained");
        var other=new DpsSignal();other.Configure(new DpsOptions{Enabled=true,Scope="party"});other.Consume(vital,0,vital.Length,1,"old-stream");byte[] energy=Energy(42);other.Consume(energy,0,energy.Length,2,"new-stream");Check(!other.Read(2).PartyKnown,"Party recovery cannot cross gameplay streams");
        s=new DpsSignal();s.Configure(new DpsOptions{Enabled=true,Scope="party"});var delta=new List<byte>(new byte[]{0x0d,0x92,0,2});delta.AddRange(Member(43,"Beta",33));Feed(s,delta.ToArray(),1);Feed(s,Identity(44,"Gamma"),2);Feed(s,Energy(42),3);Feed(s,Npc(99),3);Feed(s,Hit(43,100,false),4);Feed(s,Hit(44,200,false),4);Check(s.Read(4).Rows.Count==1,"Join received before energy must not be lost");Feed(s,Vital(44),5);Check(s.Read(5).PartyMembers==3&&s.Read(5).Rows.Count==2,"A newly observed third party member is added automatically");
        s=new DpsSignal();s.Configure(new DpsOptions{Enabled=true,Scope="party"});Feed(s,Party(true),1);for(int t=10;t<200;t+=10)Feed(s,new byte[]{1,0},t);Feed(s,Energy(42),200);Check(s.Read(200).PartyMembers==2,"An explicit roster remains valid when the first dash is delayed");
        s=new DpsSignal();s.Configure(new DpsOptions{Enabled=true,Scope="party",IdleSeconds=120});Feed(s,Energy(42),1);Feed(s,Npc(99),1);Feed(s,Vital(43),2);
        Feed(s,Hit(43,300,false),3);var unnamed=s.Read(3);Check(unnamed.PartyKnown&&unnamed.Rows.Count==1&&unnamed.Rows[0].Actor==43&&unnamed.Rows[0].Name==null&&unnamed.Rows[0].Damage==300,"Confirmed party damage must not wait for a display name");
        Check(DpsDesign.DisplayName(unnamed.Rows[0],unnamed,new DpsOptions(),"es")=="Jugador 43","Unnamed confirmed party rows have a localized temporary label");
        Feed(s,MetricHit(43,42,200,18160002,false),4);Check(Find(s.Read(4),43).Healing==200&&Find(s.Read(4),42).HealingReceived==200,"Confirmed party healing must not wait for names");
        Feed(s,Hit(44,900,false),5);Check(s.Read(5).Rows.Count==2,"Unidentified nearby actors cannot be accepted from a skill prefix alone");
        Feed(s,Identity(43,"Beta"),6);Check(Find(s.Read(6),43).Name=="Beta"&&Find(s.Read(6),43).Damage==300,"A late name updates the existing row without losing or duplicating damage");
        s=new DpsSignal();s.Configure(new DpsOptions{Enabled=true,Scope="party",IdleSeconds=120});Feed(s,Energy(42),1);Feed(s,Npc(99),1);Feed(s,Vital(43),2);Feed(s,Hit(43,300,false),3);Feed(s,Hit(43,900,false),123);Check(!s.Read(123).PartyKnown&&s.Read(123).Rows.Count==0,"Unnamed membership expires and cannot retain departed actors");
    }
    static void VerifyMotion(){
        var o=new DpsOptions{AutoHide=true,HideAfterSeconds=2,FadeSeconds=.2,SmoothingSeconds=.2};var s=DpsDesign.Sample();s.FirstImpact=1;s.LastImpact=100;var motion=new DpsMotion();motion.Set(s,o,0,100);motion.Step(0,false,o);motion.Step(.1,false,o);Check(motion.Opacity>.4&&motion.Opacity<.6&&motion.Ratios[1]>0&&motion.Ratios[1]<1,"Fade in and smooth growth");motion.Step(.2,false,o);Check(motion.Opacity>.999,"Fade reaches full opacity");
        double old=motion.Ratios[2];s.Rows[1].Damage=1000;motion.Set(s,o,.3,100.3);motion.Step(.3,false,o);motion.Step(.4,false,o);Check(motion.Ratios[2]<old&&motion.Ratios[2]>1000.0/38600,"Smooth shrinking bar");
        motion.Step(2.01,false,o);motion.Step(2.11,false,o);Check(motion.Opacity>.4&&motion.Opacity<.6,"Idle fade starts at deadline");s.LastImpact=102.11;motion.Set(s,o,2.11,102.11);motion.Step(2.11,false,o);motion.Step(2.16,false,o);Check(motion.Opacity>.7&&motion.Opacity<1,"New combat reverses fading");
        motion.Step(4.2,false,o);motion.Step(4.5,false,o);Check(motion.Opacity==0,"Hide completes");motion.Step(4.5,true,o);Check(motion.Opacity==1,"Unlocked widgets stay visible");o.AutoHide=false;motion.Step(5,false,o);Check(motion.Opacity==1,"Disabled auto hide stays visible");o.Smooth=false;motion.Step(5.1,false,o);Check(motion.Ratios[2]==1000.0/38600,"Disabling smoothing snaps to accurate ratio");o.HideAfterSeconds=double.NaN;o.FadeSeconds=double.PositiveInfinity;o.Normalize();Check(o.HideAfterSeconds==15&&o.FadeSeconds==.2,"Invalid animation settings normalized");
        o.AutoHide=true;var missing=new DpsSignal.Snapshot{NeedsIdentification=true,Status="Dash once to identify your character"};motion.Reset();motion.Set(missing,o,0,100);motion.Step(100,false,o);Check(motion.Opacity==1&&!motion.Animating,"Identification notice stays fully visible beyond inactivity deadline");missing.NeedsIdentification=false;missing.SelfActor=42;motion.Set(missing,o,101,201);motion.Step(101,false,o);motion.Step(101.3,false,o);Check(motion.Opacity==0,"Detecting character restores ordinary idle hiding");
    }
    internal static void Replay(string root,string file){var reader=new DpsSignal();reader.Configure(new DpsOptions{Enabled=true,Scope="global"});var serializer=new JavaScriptSerializer();double last=0;int frames=0;long maximumDamage=0;foreach(string line in File.ReadLines(file)){var r=serializer.Deserialize<Dictionary<string,object>>(line);string hex=(string)r["hex"];var bytes=new byte[hex.Length/2];for(int i=0;i<bytes.Length;i++)bytes[i]=Convert.ToByte(hex.Substring(i*2,2),16);last=Convert.ToDouble(r["ts"]);reader.Consume(bytes,0,bytes.Length,last,"replay");frames++;if(bytes.Length>1&&(bytes[0]==4||bytes[0]==5)&&bytes[1]==0x38){long total=0;foreach(var row in reader.Read(last).Rows)total+=row.Damage;maximumDamage=Math.Max(maximumDamage,total);}}
        File.WriteAllText(Path.Combine(root,"dps-replay-test.txt"),serializer.Serialize(new{frames=frames,maximumEncounterDamage=maximumDamage,lastSnapshot=DpsSignal.Export(reader.Read(last)),experimental=true}));Check(maximumDamage>0,"Replay did not produce attributed combat data");}
}
