using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Web.Script.Serialization;

internal static class NotificationVerification {
    static void Check(bool value,string text){if(!value)throw new Exception(text);}
    internal static void Run(string root){
        var o=new NotificationOptions();o.Normalize();var motion=new NotificationMotion();motion.Show(0);Check(motion.Step(0,o,false)&&motion.Opacity==0,"Fade must start transparent");motion.Step(.125,o,false);Check(Math.Abs(motion.Opacity-.5)<.001,"Fade must advance smoothly");motion.Step(.25,o,false);Check(motion.Opacity==1,"Fade reaches full opacity");motion.Step(6.375,o,false);Check(Math.Abs(motion.Opacity-.5)<.001,"Fade out follows the hold duration");motion.Show(6.375);motion.Step(6.4375,o,false);Check(motion.Opacity>.5&&motion.Opacity<1,"A new invite reverses a disappearing notification without a jump");Check(!motion.Step(20,o,false)&&motion.Opacity==0,"Finished notification stops animation");o.Fade=false;motion.Show(21);motion.Step(21,o,false);Check(motion.Opacity==1,"Disabled fade appears immediately");Check(!motion.Step(27,o,false)&&motion.Opacity==0,"Disabled fade expires without animation");motion.Step(30,o,true);Check(motion.Opacity==1,"Editing shows the target area without an event");motion.Clear();motion.Step(31,o,false);Check(motion.Opacity==0,"Locking an idle sample hides it");
        var source=new NotificationSignal();source.Configure(o);Check(source.EnqueueValidatedInvitation("Example",1)&&!source.EnqueueValidatedInvitation("Example",1.2)&&source.Take()=="Example"&&source.Take()==null,"Validated events must deduplicate and drain once");Check(!source.EnqueueValidatedInvitation("bad\nname",3),"Control characters cannot enter notification text");for(int i=0;i<20;i++)source.EnqueueValidatedInvitation("Example"+i,4+i);int count=0;while(source.Take()!=null)count++;Check(count==8,"Notification queue must stay bounded");o.PartyInvites=false;source.Configure(o);Check(!source.EnqueueValidatedInvitation("Example",30),"Disabled invitation category ignores events");o.PartyInvites=true;source.Configure(o);source.EnqueueValidatedInvitation("Example",31);o.Enabled=false;source.Configure(o);Check(source.Take()==null&&!source.EnqueueValidatedInvitation("Other",32),"Disabling module clears pending events");source.Reset();VerifyInvitation();
        o=new NotificationOptions{Enabled=true,Sound=false,Bounds=new Rectangle(20,40,420,90),DurationSeconds=9,Color="#123456"};var json=new JavaScriptSerializer();var restored=NotificationOptions.Read(json.Deserialize<Dictionary<string,object>>(json.Serialize(new{notifications=o})));Check(NotificationOptions.Same(o,restored),"Notification preferences must persist");var invalid=o.Copy();invalid.Color="invalid";invalid.DurationSeconds=double.NaN;invalid.Bounds=new Rectangle(0,0,1,1);invalid.Volume=999;invalid.Normalize();Check(invalid.Color=="#EEEEEE"&&invalid.DurationSeconds==6&&invalid.Bounds.Width==260&&invalid.Bounds.Height==60&&invalid.Volume==100,"Invalid preferences must have safe limits");var start=new Rectangle(100,100,440,90);var resized=NotificationDesign.Resize(start,new Point(400,400),13);Check(resized.Width==260&&resized.Height==60&&resized.Right==start.Right&&resized.Bottom==start.Bottom,"Top-left resize preserves the opposite corner");
        string designs=Path.Combine(root,"designs");Directory.CreateDirectory(designs);using(var workspace=new FpsDesign.Workspace()){foreach(string language in new[]{"en","es"})using(var bitmap=NotificationDesign.Render(440,90,"Example",language,new NotificationOptions(),false,workspace)){Check(bitmap.GetPixel(0,0).A==0&&bitmap.GetPixel(220,80).A>0,"Transparent corners and dark body");bitmap.Save(Path.Combine(designs,"notification-"+language+".png"));}}
        using(var owner=new EnergyOverlay(root,true)){using(var overlay=new NotificationOverlay(owner,root,new NotificationSignal(),true))overlay.VerifyNative();var settings=new HelperSettings(owner);try{settings.VerifyNotifications(root);}finally{settings.Close();}}
        using(var audio=new NotificationAudio(Path.Combine(root,"missing-sound-fixture"))){audio.Play(80);Check(audio.Error=="Notification sound file is missing.","Missing sound must report an error without breaking notices");}
        Check(File.Exists(Path.Combine(root,"assets","sounds","party-invite.mp3")),"User sound asset must be included locally");
        File.WriteAllText(Path.Combine(root,"notifications-test.txt"),"PASS: incoming invitation layout and UTF8 names; complete bounds/truncation/malformed checks; roster rejection; request-token deduplication; timed fades and reversal; disabled fades; editing/locking; bounded event queue; enable/category gates; persisted preferences; safe normalization/resize; crisp EN/ES alpha renders; settings undo, disabled controls and localization; cached settings and native presentations; independent fade/hold deadlines; bounded GDI resources after resize; missing audio handling.");
    }
    static byte[] Invite(string name,ulong token){byte[] utf8=System.Text.Encoding.UTF8.GetBytes(name),b=new byte[54+utf8.Length];b[0]=9;b[1]=0x92;Array.Copy(BitConverter.GetBytes(1UL),0,b,2,8);b[10]=2;b[16]=0x15;b[17]=5;Array.Copy(BitConverter.GetBytes(33U),0,b,18,4);b[30]=(byte)utf8.Length;Array.Copy(utf8,0,b,31,utf8.Length);int tail=31+utf8.Length;b[tail]=0x15;b[tail+1]=5;b[tail+14]=1;Array.Copy(BitConverter.GetBytes(token),0,b,tail+15,8);return b;}
    static void VerifyInvitation(){string name,key;foreach(string player in new[]{"Example","Élan","玩家","Player_2"}){var b=Invite(player,123);Check(NotificationSignal.Invitation(b,0,b.Length,out name,out key)&&name==player,"Invitation must decode valid UTF8 player names");for(int end=0;end<b.Length;end++)Check(!NotificationSignal.Invitation(b,0,end,out name,out key),"Truncated invitation cannot fire");var offset=new byte[b.Length+9];Array.Copy(b,0,offset,4,b.Length);Check(NotificationSignal.Invitation(offset,4,4+b.Length,out name,out key)&&name==player,"Decoder respects frame offsets");b[31+b[30]+2]=1;Check(!NotificationSignal.Invitation(b,0,b.Length,out name,out key),"Unexpected invitation tail rejected");}var bad=Invite("Example",123);bad[31]=255;Check(!NotificationSignal.Invitation(bad,0,bad.Length,out name,out key),"Invalid UTF8 cannot fire");bad=Invite("Example",123);bad[0]=0;Check(!NotificationSignal.Invitation(bad,0,bad.Length,out name,out key),"Party roster opcode cannot fire");Check(!NotificationSignal.Invitation(null,0,10,out name,out key),"Null frame ignored");Check(!NotificationSignal.Invitation(bad,-1,20,out name,out key),"Negative bounds ignored");var signal=new NotificationSignal();var o=new NotificationOptions();signal.Configure(o);var first=Invite("Example",1);signal.Consume(first,0,first.Length,1,"flow");signal.Consume(first,0,first.Length,6,"flow");Check(signal.Received==1&&signal.Take()=="Example"&&signal.Take()==null,"Repeated event token triggers only once, even after two seconds");first=Invite("Example",2);signal.Consume(first,0,first.Length,7,"flow");Check(signal.Received==2&&signal.Take()=="Example","A new invitation from the same player triggers again");o.Sound=false;signal.Configure(o);first=Invite("Example",3);signal.Consume(first,0,first.Length,8,"flow");Check(signal.Take()=="Example","Muting audio must retain visual notification events");o.Enabled=false;signal.Configure(o);first=Invite("Example",4);signal.Consume(first,0,first.Length,9,"flow");Check(signal.Received==3&&signal.Take()==null,"Disabled module never queues real invitations");}
}
