using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using Drawing=System.Drawing;

internal sealed class NotificationSettingsPane:Grid {
    readonly EnergyOverlay owner;readonly Window window;readonly CheckBox enabled=new CheckBox(),party=new CheckBox(),dungeon=new CheckBox(),shugo=new CheckBox(),shugoOpening=new CheckBox(),sound=new CheckBox(),fade=new CheckBox();readonly Dictionary<string,SettingsNumber> numbers=new Dictionary<string,SettingsNumber>();readonly StackPanel controls=new StackPanel();readonly ScrollViewer scroll;readonly Image preview=new Image{Height=95,Stretch=System.Windows.Media.Stretch.None};readonly Border previewCard;readonly Button color,test,shugoTest,openingTest;readonly TextBlock status=SettingsVisual.Text("",11,"#8994A6");bool loading,released;string colorHex,lastLanguage,previewLanguage,swatchColor;NotificationOptions lastOptions,previewOptions;FpsDesign.Workspace previewWorkspace;
    internal NotificationSettingsPane(EnergyOverlay parent,Window settings){owner=parent;window=settings;RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});
        var activation=Row("Enable all notifications");activation.Margin=new Thickness(0,0,0,16);Grid.SetColumn(enabled,1);activation.Children.Add(enabled);Children.Add(activation);AutomationProperties.SetName(enabled,"Enable all notifications");enabled.Click+=delegate{if(loading)return;var c=owner.Configuration;c.Notifications.Enabled=enabled.IsChecked==true;owner.ApplyConfiguration(c);};
        var sample=new StackPanel();sample.Children.Add(SettingsVisual.Text("PREVIEW",10,"#929CAD"));sample.Children.Add(preview);sample.Children.Add(SettingsVisual.Text("Sample notification · not a game event",11,"#8994A6"));previewCard=SettingsVisual.Card(sample,new Thickness(18,12,18,12));Grid.SetRow(previewCard,1);Children.Add(previewCard);
        controls.Margin=new Thickness(0,0,12,0);scroll=new ScrollViewer{Content=controls,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};scroll.SetResourceReference(FrameworkElement.StyleProperty,"SlimScroll");Grid.SetRow(scroll,2);Children.Add(scroll);
        var group=Group("NOTIFICATION TYPES");Toggle(group,"Party invitations",party);Toggle(group,"Dungeon party invitations",dungeon);Toggle(group,"Shugo Festival · 5 minutes before",shugo);Toggle(group,"Shugo Festival · registration opens",shugoOpening);var scheduleHelp=SettingsVisual.Text("Reminders at :55 and :00 while Aion 2 is open. Turn each one on or off independently.",11,"#8994A6");scheduleHelp.Margin=new Thickness(0,6,0,8);group.Children.Add(scheduleHelp);shugoTest=SettingsVisual.Button("Test 5-minute reminder",owner.TestShugoNotification);shugoTest.HorizontalAlignment=HorizontalAlignment.Left;shugoTest.Margin=new Thickness(0,0,0,8);var testRow=new StackPanel{Orientation=Orientation.Horizontal};shugoTest.Margin=new Thickness(0,0,8,8);testRow.Children.Add(shugoTest);openingTest=SettingsVisual.Button("Test opening reminder",owner.TestShugoOpeningNotification);openingTest.HorizontalAlignment=HorizontalAlignment.Left;openingTest.Margin=new Thickness(0,0,0,8);testRow.Children.Add(openingTest);group.Children.Add(testRow);
        var help=SettingsVisual.Text("Choose which notifications you want to receive. Turning all notifications off keeps your individual choices.",11,"#8994A6");help.Margin=new Thickness(0,6,0,4);group.Children.Add(help);
        group=Group("COMMON SETTINGS");var shared=SettingsVisual.Text("Sound, duration, appearance and position apply to all notification types.",11,"#8994A6");shared.Margin=new Thickness(0,0,0,8);group.Children.Add(shared);Toggle(group,"Play notification sound",sound);Number(group,"Volume","Sound volume","%",0,100,0,5);Number(group,"Duration","Notification duration","s",1,60,1,.5M);Toggle(group,"Fade in and out",fade);Number(group,"Fade","Fade duration","ms",0,2000,0,50);
        test=SettingsVisual.Button("Test notification",owner.TestNotification,true);test.HorizontalAlignment=HorizontalAlignment.Left;test.Margin=new Thickness(0,12,0,12);group.Children.Add(test);group.Children.Add(status);
        group=Group("APPEARANCE");var colorRow=Row("Text color");color=SettingsVisual.Button("",PickColor);color.MinWidth=152;Grid.SetColumn(color,1);colorRow.Children.Add(color);group.Children.Add(colorRow);Number(group,"Opacity","Background opacity","%",0,100,0,5);Number(group,"Font","Text size","px",10,48,0,1);
        group=Group("POSITION & SIZE");Number(group,"X","Horizontal position","px",-100000,100000,0,10);Number(group,"Y","Vertical position","px",-100000,100000,0,10);Number(group,"Width","Width","px",260,1600,0,10);Number(group,"Height","Height","px",60,500,0,5);
        var note=SettingsVisual.Text("Unlock widgets to move or resize the notification area. A sample stays visible while editing; it does not play a sound.",11,"#8994A6");note.Margin=new Thickness(2,0,0,12);controls.Children.Add(note);
        foreach(var toggle in new[]{party,dungeon,shugo,shugoOpening,sound,fade})toggle.Click+=delegate{Changed();};foreach(var field in numbers.Values)field.Changed+=Changed;Reload();
    }
    StackPanel Group(string title){controls.Children.Add(SettingsVisual.Text(title,10,"#929CAD"));var content=new StackPanel();var card=SettingsVisual.Card(content,new Thickness(18,12,18,12));card.Margin=new Thickness(0,8,0,18);controls.Children.Add(card);return content;}
    Grid Row(string label){var row=new Grid{Margin=new Thickness(0,7,0,7)};row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});row.Children.Add(SettingsVisual.Text(label));return row;}
    void Toggle(StackPanel group,string label,CheckBox toggle){var row=Row(label);Grid.SetColumn(toggle,1);row.Children.Add(toggle);AutomationProperties.SetName(toggle,label);group.Children.Add(row);}
    void Number(StackPanel group,string key,string label,string suffix,decimal min,decimal max,int decimals,decimal step){var row=Row(label);var holder=new StackPanel{Orientation=Orientation.Horizontal};Grid.SetColumn(holder,1);row.Children.Add(holder);var field=new SettingsNumber(label,min,max,decimals,step);numbers[key]=field;holder.Children.Add(field);holder.Children.Add(new TextBlock{Text=suffix,Foreground=SettingsVisual.Brush("#8994A6"),Width=28,Margin=new Thickness(8,0,0,0),VerticalAlignment=VerticalAlignment.Center});group.Children.Add(row);}
    void Changed(){if(loading)return;var c=owner.Configuration;var o=c.Notifications;o.PartyInvites=party.IsChecked==true;o.DungeonInvites=dungeon.IsChecked==true;o.ShugoFestival=shugo.IsChecked==true;o.ShugoOpening=shugoOpening.IsChecked==true;o.Sound=sound.IsChecked==true;o.Fade=fade.IsChecked==true;o.Color=colorHex;o.Volume=(int)numbers["Volume"].Value;o.DurationSeconds=(double)numbers["Duration"].Value;o.FadeSeconds=(double)numbers["Fade"].Value/1000;o.BackgroundOpacity=(int)Math.Round((double)numbers["Opacity"].Value*255/100);o.FontSize=(int)numbers["Font"].Value;o.Bounds=new Drawing.Rectangle((int)numbers["X"].Value,(int)numbers["Y"].Value,(int)numbers["Width"].Value,(int)numbers["Height"].Value);owner.ApplyConfiguration(c);}
    void PickColor(){var picker=new HelperColorPicker(colorHex,"Text color",owner.Language){Owner=window};if(picker.ShowDialog()==true){colorHex=picker.SelectedHex;Changed();}}
    internal void Reload(){if(released)return;var o=owner.Configuration.Notifications;string language=owner.Language;if(lastOptions!=null&&NotificationOptions.Same(lastOptions,o)&&lastLanguage==language){UpdateStatus();return;}loading=true;try{enabled.IsChecked=o.Enabled;party.IsChecked=o.PartyInvites;dungeon.IsChecked=o.DungeonInvites;shugo.IsChecked=o.ShugoFestival;shugoOpening.IsChecked=o.ShugoOpening;sound.IsChecked=o.Sound;fade.IsChecked=o.Fade;colorHex=o.Color;numbers["Volume"].Value=o.Volume;numbers["Duration"].Value=(decimal)o.DurationSeconds;numbers["Fade"].Value=(decimal)(o.FadeSeconds*1000);numbers["Opacity"].Value=(decimal)(o.BackgroundOpacity*100.0/255);numbers["Font"].Value=o.FontSize;numbers["X"].Value=o.Bounds.X;numbers["Y"].Value=o.Bounds.Y;numbers["Width"].Value=o.Bounds.Width;numbers["Height"].Value=o.Bounds.Height;if(swatchColor!=colorHex){var swatch=new StackPanel{Orientation=Orientation.Horizontal};swatch.Children.Add(new Border{Width=17,Height=17,CornerRadius=new CornerRadius(5),Background=SettingsVisual.Brush(colorHex),Margin=new Thickness(0,0,9,0)});swatch.Children.Add(SettingsVisual.Text(colorHex,12));color.Content=swatch;swatchColor=colorHex;}scroll.IsEnabled=o.Enabled;scroll.Opacity=o.Enabled?1:.45;previewCard.Opacity=o.Enabled?1:.38;shugoTest.IsEnabled=o.ShugoFestival;openingTest.IsEnabled=o.ShugoOpening;numbers["Volume"].IsEnabled=o.Sound;numbers["Fade"].IsEnabled=o.Fade;if(previewOptions==null||!NotificationOptions.SameAppearance(previewOptions,o)||previewLanguage!=language){if(previewWorkspace==null)previewWorkspace=new FpsDesign.Workspace();using(var image=NotificationDesign.Render(540,90,null,language,o,false,previewWorkspace))preview.Source=SettingsVisual.Bitmap(image);previewOptions=o.Copy();previewLanguage=language;}if(lastLanguage!=language)UiLanguage.Apply(this,language);lastOptions=o.Copy();lastLanguage=language;UpdateStatus();}finally{loading=false;}}
    internal void Release(){if(released)return;released=true;preview.Source=null;lastOptions=previewOptions=null;if(previewWorkspace!=null){previewWorkspace.Dispose();previewWorkspace=null;}}
    internal void UpdateStatus(){string value=UiLanguage.Text(owner.NotificationStatus,owner.Language);if(status.Text!=value)status.Text=value;}
    void VerifyPreviewCache(){
        var image=preview.Source;for(int i=0;i<100;i++)Reload();if(!object.ReferenceEquals(image,preview.Source))throw new Exception("Unchanged settings must reuse the frozen notification preview");
        var original=owner.Configuration;var c=original.Copy();c.Notifications.Volume=(c.Notifications.Volume+5)%101;c.Notifications.Bounds.X+=10;owner.ApplyConfiguration(c);Reload();if(!object.ReferenceEquals(image,preview.Source))throw new Exception("Volume and position must not regenerate preview pixels");
        c.Notifications.Color="#654321";owner.ApplyConfiguration(c);Reload();if(object.ReferenceEquals(image,preview.Source))throw new Exception("Visual settings must refresh the preview");owner.ApplyConfiguration(original);Reload();
    }
    internal void Verify(){var original=owner.Configuration;var c=original.Copy();c.Notifications.Enabled=true;c.Notifications.Sound=false;c.Notifications.DurationSeconds=9;c.Notifications.BackgroundOpacity=180;c.Notifications.Color="#123456";owner.ApplyConfiguration(c);Reload();VerifyPreviewCache();if(sound.IsChecked!=false||numbers["Duration"].Value!=9||numbers["Volume"].IsEnabled||colorHex!="#123456")throw new Exception("Notification controls must restore preferences");sound.IsChecked=true;Changed();if(!owner.Configuration.Notifications.Sound)throw new Exception("Notification sound switch must apply");owner.UndoConfiguration();if(!ConfigurationHistory.Same(c,owner.Configuration))throw new Exception("Notification settings must support undo without changing other modules");owner.ApplyConfiguration(c);Reload();party.IsChecked=false;Changed();Reload();var individual=owner.Configuration;if(individual.Notifications.PartyInvites||!scroll.IsEnabled||!color.IsEnabled)throw new Exception("Disabling one notification type must keep common settings editable");var off=individual.Copy();off.Notifications.Enabled=false;owner.ApplyConfiguration(off);var on=owner.Configuration;on.Notifications.Enabled=true;owner.ApplyConfiguration(on);Reload();if(party.IsChecked!=false||!NotificationOptions.Same(individual.Notifications,owner.Configuration.Notifications))throw new Exception("Global notification toggle must preserve individual choices and shared settings");dungeon.IsChecked=false;Changed();Reload();if(owner.Configuration.Notifications.DungeonInvites||owner.Configuration.Notifications.PartyInvites||!scroll.IsEnabled)throw new Exception("Dungeon category must apply independently");owner.UndoConfiguration();Reload();if(!owner.Configuration.Notifications.DungeonInvites||owner.Configuration.Notifications.PartyInvites||dungeon.IsChecked!=true)throw new Exception("Dungeon category supports undo independently of normal invites");shugo.IsChecked=false;Changed();Reload();if(owner.Configuration.Notifications.ShugoFestival||!scroll.IsEnabled)throw new Exception("Shugo category applies independently");owner.UndoConfiguration();if(!owner.Configuration.Notifications.ShugoFestival)throw new Exception("Shugo category supports undo");shugoOpening.IsChecked=false;Changed();Reload();if(owner.Configuration.Notifications.ShugoOpening||!owner.Configuration.Notifications.ShugoFestival)throw new Exception("Opening toggle must preserve advance preference");owner.UndoConfiguration();if(!owner.Configuration.Notifications.ShugoOpening)throw new Exception("Opening toggle supports undo");owner.ApplyConfiguration(original);c=original.Copy();c.Notifications.Enabled=false;owner.ApplyConfiguration(c);Reload();if(scroll.IsEnabled||!enabled.IsEnabled)throw new Exception("Disabled notifications must block controls but keep activation");owner.ApplyConfiguration(original);}
}
