using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Web.Script.Serialization;

internal static class NotificationVerification {
    static void Check(bool value,string text){if(!value)throw new Exception(text);}
    internal static void Run(string root){
        VerifyShugo();VerifyDungeonInvitation();VerifyInvitationChoices();
        var o=new NotificationOptions();o.Normalize();var motion=new NotificationMotion();motion.Show(0);Check(motion.Step(0,o,false)&&motion.Opacity==0,"Fade must start transparent");motion.Step(.125,o,false);Check(Math.Abs(motion.Opacity-.5)<.001,"Fade must advance smoothly");motion.Step(.25,o,false);Check(motion.Opacity==1,"Fade reaches full opacity");motion.Step(6.375,o,false);Check(Math.Abs(motion.Opacity-.5)<.001,"Fade out follows the hold duration");motion.Show(6.375);motion.Step(6.4375,o,false);Check(motion.Opacity>.5&&motion.Opacity<1,"A new invite reverses a disappearing notification without a jump");Check(!motion.Step(20,o,false)&&motion.Opacity==0,"Finished notification stops animation");o.Fade=false;motion.Show(21);motion.Step(21,o,false);Check(motion.Opacity==1,"Disabled fade appears immediately");Check(!motion.Step(27,o,false)&&motion.Opacity==0,"Disabled fade expires without animation");motion.Step(30,o,true);Check(motion.Opacity==1,"Editing shows the target area without an event");motion.Clear();motion.Step(31,o,false);Check(motion.Opacity==0,"Locking an idle sample hides it");
        var source=new NotificationSignal();source.Configure(o);Check(source.EnqueueValidatedInvitation("Example",1)&&!source.EnqueueValidatedInvitation("Example",1.2)&&source.Take()=="Example"&&source.Take()==null,"Validated events must deduplicate and drain once");Check(!source.EnqueueValidatedInvitation("bad\nname",3),"Control characters cannot enter notification text");for(int i=0;i<20;i++)source.EnqueueValidatedInvitation("Example"+i,4+i);int count=0;while(source.Take()!=null)count++;Check(count==8,"Notification queue must stay bounded");o.PartyInvites=false;source.Configure(o);Check(!source.EnqueueValidatedInvitation("Example",30),"Disabled invitation category ignores events");o.PartyInvites=true;source.Configure(o);source.EnqueueValidatedInvitation("Example",31);o.Enabled=false;source.Configure(o);Check(source.Take()==null&&!source.EnqueueValidatedInvitation("Other",32),"Disabling module clears pending events");source.Reset();VerifyInvitation();
        o=new NotificationOptions{Enabled=true,Sound=false,Bounds=new Rectangle(20,40,420,90),DurationSeconds=9,Color="#123456"};var json=new JavaScriptSerializer();var restored=NotificationOptions.Read(json.Deserialize<Dictionary<string,object>>(json.Serialize(new{notifications=o})));Check(NotificationOptions.Same(o,restored),"Notification preferences must persist");var invalid=o.Copy();invalid.Color="invalid";invalid.DurationSeconds=double.NaN;invalid.Bounds=new Rectangle(0,0,1,1);invalid.Volume=999;invalid.Normalize();Check(invalid.Color=="#EEEEEE"&&invalid.DurationSeconds==6&&invalid.Bounds.Width==260&&invalid.Bounds.Height==60&&invalid.Volume==100,"Invalid preferences must have safe limits");var start=new Rectangle(100,100,440,90);var resized=NotificationDesign.Resize(start,new Point(400,400),13);Check(resized.Width==260&&resized.Height==60&&resized.Right==start.Right&&resized.Bottom==start.Bottom,"Top-left resize preserves the opposite corner");
        string designs=Path.Combine(root,"designs");Directory.CreateDirectory(designs);using(var workspace=new FpsDesign.Workspace()){foreach(string language in new[]{"en","es"})using(var bitmap=NotificationDesign.Render(440,90,"Example",language,new NotificationOptions(),false,workspace)){Check(bitmap.GetPixel(0,0).A==0&&bitmap.GetPixel(220,80).A>0,"Transparent corners and dark body");bitmap.Save(Path.Combine(designs,"notification-"+language+".png"));}foreach(string language in new[]{"en","es"})using(var bitmap=NotificationDesign.Render(440,90,"Example",language,new NotificationOptions(),false,workspace,false,false,true)){bitmap.Save(Path.Combine(designs,"notification-dungeon-"+language+".png"));}}
        using(var owner=new EnergyOverlay(root,true)){using(var overlay=new NotificationOverlay(owner,root,new NotificationSignal(),true)){overlay.VerifyNative();overlay.VerifyShugoNative();overlay.VerifyDungeonNative();}var settings=new HelperSettings(owner);try{settings.VerifyNotifications(root);}finally{settings.Close();}}
        using(var audio=new NotificationAudio(Path.Combine(root,"missing-sound-fixture"))){audio.Play(80);Check(audio.Error=="Notification sound file is missing.","Missing sound must report an error without breaking notices");}
        Check(File.Exists(Path.Combine(root,"assets","sounds","party-invite.mp3")),"User sound asset must be included locally");
        File.WriteAllText(Path.Combine(root,"notifications-test.txt"),"PASS: normal and dungeon invitation layouts, typed independent queues/gates/deduplication, persisted choices and capture demand; localized dungeon text and native category dismissal; incoming invitation layout and UTF8 names; complete bounds/truncation/malformed checks; roster rejection; request-token deduplication; timed fades and reversal; disabled fades; editing/locking; bounded event queue; enable/category gates; persisted preferences; safe normalization/resize; crisp EN/ES alpha renders; settings undo, disabled controls and localization; cached settings and native presentations; independent fade/hold deadlines; bounded GDI resources after resize; missing audio handling.");
    }
    static void VerifyShugo(){
        var schedule=new ShugoSchedule();DateTime now=new DateTime(2026,10,10,18,54,59,DateTimeKind.Utc);
        Check(!schedule.Due(now)&&schedule.Due(now.AddSeconds(1)),"Shugo fires at55, not54");
        Check(!schedule.Due(now.AddSeconds(30))&&!schedule.Due(now.AddMinutes(1)),"Shugo deduplicates within the same hour");
        Check(!schedule.Due(now.AddMinutes(2))&&!schedule.Due(now.AddMinutes(5)),"No late or on-hour reminder");
        Check(schedule.Due(now.AddHours(1).AddSeconds(1)),"Following hour fires again");
        Check(!schedule.Due(now.AddSeconds(1)),"Backward clock does not replay an older hour");
        var midnight=new ShugoSchedule();Check(midnight.Due(new DateTime(2026,10,10,23,55,0,DateTimeKind.Utc))&&midnight.Due(new DateTime(2026,10,11,0,55,0,DateTimeKind.Utc)),"Date rollover preserves hourly events");
        Check(ShugoSchedule.NextCheck(now)==1000&&ShugoSchedule.NextCheck(now.AddSeconds(1))==60000,"Minute deadline avoids constant polling");
        Check(UiLanguage.Text("Shugo Festival starts in 5 minutes.","es")=="El festival de Shugo empieza en 5 minutos.","Shugo message localized");
        var old=NotificationOptions.Read(new JavaScriptSerializer().Deserialize<Dictionary<string,object>>("{\"notifications\":{\"Enabled\":true,\"PartyInvites\":false}}"));Check(old.ShugoFestival&&!old.PartyInvites,"Existing settings gain the new reminder without restoring disabled party alerts");
        var copy=old.Copy();copy.ShugoFestival=false;Check(!NotificationOptions.Same(copy,old),"Shugo choice participates in undo/equality");
        Check(old.ShugoOpening,"Legacy preferences enable the new opening notice");copy=old.Copy();copy.ShugoOpening=false;Check(!NotificationOptions.Same(copy,old),"Opening preference participates in undo/equality");
        var both=new ShugoSchedule();DateTime advance=new DateTime(2026,10,10,23,55,0,DateTimeKind.Utc),open=advance.AddMinutes(5);
        Check(both.Due(advance)&&!both.DueOpening(advance)&&both.DueOpening(open)&&!both.Due(open),"Advance and opening fire separately across midnight");
        Check(!both.DueOpening(open.AddSeconds(30))&&!both.DueOpening(open.AddMinutes(1)),"Opening fires only once and does not catch up late");
        Check(both.DueOpening(open.AddHours(1))&&!both.DueOpening(open),"Opening repeats next hour without backward-clock duplication");
        Check(UiLanguage.Text("You can now sign up for Shugo Festival.","es")=="Ya puedes apuntarte al festival de Shugo.","Opening message localized");
    }
    static byte[] Invite(string name,ulong token){byte[] utf8=System.Text.Encoding.UTF8.GetBytes(name),b=new byte[54+utf8.Length];b[0]=9;b[1]=0x92;Array.Copy(BitConverter.GetBytes(1UL),0,b,2,8);b[10]=2;b[16]=0x15;b[17]=5;Array.Copy(BitConverter.GetBytes(33U),0,b,18,4);b[30]=(byte)utf8.Length;Array.Copy(utf8,0,b,31,utf8.Length);int tail=31+utf8.Length;b[tail]=0x15;b[tail+1]=5;b[tail+14]=1;Array.Copy(BitConverter.GetBytes(token),0,b,tail+15,8);return b;}
    static byte[] DungeonInvite(string name,ulong token){var normal=Invite(name,token);var b=new byte[normal.Length+1];Array.Copy(normal,0,b,0,10);b[0]=0x0e;b[1]=0x97;Array.Copy(normal,10,b,11,normal.Length-10);return b;}
    static void VerifyDungeonInvitation(){
        string name,key,normalKey;
        foreach(string player in new[]{"Example","Élan","玩家","Player_2"}){
            var b=DungeonInvite(player,123);
            Check(NotificationSignal.Invitation(b,0,b.Length,out name,out key)&&name==player,"Dungeon invitation decodes UTF8 sender");
            var normal=Invite(player,123);Check(NotificationSignal.Invitation(normal,0,normal.Length,out name,out normalKey)&&key!=normalKey,"Normal and dungeon requests remain distinct even with identical IDs/token");
            for(int end=0;end<b.Length;end++)Check(!NotificationSignal.Invitation(b,0,end,out name,out key),"Truncated dungeon invitation rejected");
            var offset=new byte[b.Length+9];Array.Copy(b,0,offset,4,b.Length);Check(NotificationSignal.Invitation(offset,4,4+b.Length,out name,out key)&&name==player,"Dungeon invitation honors frame offsets");
        }
        // Synthetic identities; reproduce the observed one-byte prefix and tail.
        var good=DungeonInvite("Example",123);int tail=32+good[31];
        foreach(int index in new[]{10,tail,tail+2,tail+14}){var bad=(byte[])good.Clone();bad[index]^=1;Check(!NotificationSignal.Invitation(bad,0,bad.Length,out name,out key),"Malformed dungeon prefix, realm or tail rejected");}
        foreach(int start in new[]{2,11,tail+15}){var bad=(byte[])good.Clone();Array.Clear(bad,start,start==11?6:8);Check(!NotificationSignal.Invitation(bad,0,bad.Length,out name,out key),"Missing dungeon identity/token rejected");}
        var invalid=(byte[])good.Clone();invalid[32]=255;Check(!NotificationSignal.Invitation(invalid,0,invalid.Length,out name,out key),"Dungeon invalid UTF8 rejected");
        foreach(byte opcode in new byte[]{0,2,13}){var bad=(byte[])good.Clone();bad[0]=opcode;Check(!NotificationSignal.Invitation(bad,0,bad.Length,out name,out key),"Roster and recruitment messages do not fire invitations");}
        invalid=(byte[])good.Clone();invalid[0]=9;invalid[1]=0x92;Check(!NotificationSignal.Invitation(invalid,0,invalid.Length,out name,out key),"Dungeon body cannot masquerade as normal invitation");
        invalid=Invite("Example",123);invalid[0]=0x0e;invalid[1]=0x97;Check(!NotificationSignal.Invitation(invalid,0,invalid.Length,out name,out key),"Normal body cannot masquerade as dungeon invitation");
        Check(!NotificationSignal.Invitation(good,-1,good.Length,out name,out key)&&!NotificationSignal.Invitation(good,0,good.Length+1,out name,out key),"Invalid dungeon frame bounds rejected");
        var signal=new NotificationSignal();var o=new NotificationOptions();signal.Configure(o);int wakes=0;signal.OnPending=delegate{wakes++;};
        var first=Invite("Example",1);signal.Consume(first,0,first.Length,1,"flow");first=DungeonInvite("Example",1);signal.Consume(first,0,first.Length,2,"flow");signal.Consume(first,0,first.Length,7,"flow");
        Check(signal.Received==2&&wakes==2&&signal.Take()=="Example"&&signal.Take()=="Example"&&signal.Take()==null,"Normal followed by dungeon invitation fires both once");
        first=DungeonInvite("Example",2);signal.Consume(first,0,first.Length,8,"flow");Check(signal.Received==3&&signal.Take()=="Example","A new dungeon request from same sender fires again");
        o.Sound=false;signal.Configure(o);first=DungeonInvite("Example",3);signal.Consume(first,0,first.Length,9,"flow");Check(signal.Received==4&&signal.Take()=="Example","Muted dungeon invitation keeps visual event");
        o.DungeonInvites=false;signal.Configure(o);first=DungeonInvite("Example",4);signal.Consume(first,0,first.Length,10,"flow");Check(signal.Received==4&&signal.Take()==null,"Dungeon category switch blocks dungeon invitations");
        o.PartyInvites=true;o.Enabled=false;signal.Configure(o);signal.Consume(first,0,first.Length,11,"flow");Check(signal.Received==4&&signal.Take()==null,"Global switch blocks dungeon invitations");
    }
    static void VerifyInvitationChoices(){
        var options=new NotificationOptions();var signal=new NotificationSignal();signal.Configure(options);
        var normal=Invite("Example",100);var dungeon=DungeonInvite("Example",100);
        signal.Consume(normal,0,normal.Length,1,"flow");signal.Consume(dungeon,0,dungeon.Length,2,"flow");
        options.PartyInvites=false;signal.Configure(options);var notice=signal.TakeNotice();Check(notice!=null&&notice.Name=="Example"&&notice.Dungeon&&signal.TakeNotice()==null,"Disabling normal invitations removes only their queued notices");
        signal.Consume(dungeon,0,dungeon.Length,3,"flow");Check(signal.TakeNotice()==null,"Changing unrelated toggle preserves dungeon deduplication");
        normal=Invite("Other",101);dungeon=DungeonInvite("Other",101);signal.Consume(normal,0,normal.Length,4,"flow");signal.Consume(dungeon,0,dungeon.Length,4,"flow");notice=signal.TakeNotice();Check(notice!=null&&notice.Dungeon&&signal.TakeNotice()==null,"Dungeon enabled alone listens independently");
        options.PartyInvites=true;signal.Configure(options);normal=Invite("Example",102);dungeon=DungeonInvite("Example",102);signal.Consume(normal,0,normal.Length,5,"flow");signal.Consume(dungeon,0,dungeon.Length,5,"flow");options.DungeonInvites=false;signal.Configure(options);notice=signal.TakeNotice();Check(notice!=null&&!notice.Dungeon&&signal.TakeNotice()==null,"Disabling dungeon invitations removes only dungeon notices");
        normal=Invite("Other",103);dungeon=DungeonInvite("Other",103);signal.Consume(normal,0,normal.Length,6,"flow");signal.Consume(dungeon,0,dungeon.Length,6,"flow");notice=signal.TakeNotice();Check(notice!=null&&!notice.Dungeon&&signal.TakeNotice()==null,"Normal enabled alone ignores dungeon invitations");
        options.PartyInvites=false;Check(!options.NeedsCapture,"Both invitation categories off require no packet capture");options.DungeonInvites=true;Check(options.NeedsCapture,"Dungeon-only notifications keep capture enabled");options.Enabled=false;Check(!options.NeedsCapture,"Global off never requires notification capture");
        var json=new JavaScriptSerializer();var legacy=NotificationOptions.Read(json.Deserialize<Dictionary<string,object>>("{\"notifications\":{\"PartyInvites\":false}}"));Check(legacy.DungeonInvites&&!legacy.PartyInvites,"Old preferences gain independent dungeon category without enabling normal invites");
        var copy=legacy.Copy();copy.DungeonInvites=false;Check(!NotificationOptions.Same(copy,legacy),"Dungeon category participates in undo/equality");var restored=NotificationOptions.Read(json.Deserialize<Dictionary<string,object>>(json.Serialize(new{notifications=copy})));Check(!restored.DungeonInvites&&!restored.PartyInvites,"Independent disabled choices survive persistence");
        Check(UiLanguage.Text("{0} is inviting you to a dungeon party.","es")=="{0} te está invitando a un grupo de dungeon.","Dungeon message is localized");
        Check(UiLanguage.Text("Dungeon party invitations","es")=="Invitaciones al grupo de dungeon","Dungeon setting is localized");
    }
    static void VerifyInvitation(){string name,key;foreach(string player in new[]{"Example","Élan","玩家","Player_2"}){var b=Invite(player,123);Check(NotificationSignal.Invitation(b,0,b.Length,out name,out key)&&name==player,"Invitation must decode valid UTF8 player names");for(int end=0;end<b.Length;end++)Check(!NotificationSignal.Invitation(b,0,end,out name,out key),"Truncated invitation cannot fire");var offset=new byte[b.Length+9];Array.Copy(b,0,offset,4,b.Length);Check(NotificationSignal.Invitation(offset,4,4+b.Length,out name,out key)&&name==player,"Decoder respects frame offsets");b[31+b[30]+2]=1;Check(!NotificationSignal.Invitation(b,0,b.Length,out name,out key),"Unexpected invitation tail rejected");}var bad=Invite("Example",123);bad[31]=255;Check(!NotificationSignal.Invitation(bad,0,bad.Length,out name,out key),"Invalid UTF8 cannot fire");bad=Invite("Example",123);bad[0]=0;Check(!NotificationSignal.Invitation(bad,0,bad.Length,out name,out key),"Party roster opcode cannot fire");Check(!NotificationSignal.Invitation(null,0,10,out name,out key),"Null frame ignored");Check(!NotificationSignal.Invitation(bad,-1,20,out name,out key),"Negative bounds ignored");var signal=new NotificationSignal();var o=new NotificationOptions();signal.Configure(o);var first=Invite("Example",1);signal.Consume(first,0,first.Length,1,"flow");signal.Consume(first,0,first.Length,6,"flow");Check(signal.Received==1&&signal.Take()=="Example"&&signal.Take()==null,"Repeated event token triggers only once, even after two seconds");first=Invite("Example",2);signal.Consume(first,0,first.Length,7,"flow");Check(signal.Received==2&&signal.Take()=="Example","A new invitation from the same player triggers again");o.Sound=false;signal.Configure(o);first=Invite("Example",3);signal.Consume(first,0,first.Length,8,"flow");Check(signal.Take()=="Example","Muting audio must retain visual notification events");o.Enabled=false;signal.Configure(o);first=Invite("Example",4);signal.Consume(first,0,first.Length,9,"flow");Check(signal.Received==3&&signal.Take()==null,"Disabled module never queues real invitations");}
}
